package com.zsh.labouCapital.dao.client;

import com.zsh.labouCapital.dao.dto.TAnalyseAvglineResult;
import com.zsh.labouCapital.dao.dto.TAnalyseAvglineResultCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAnalyseAvglineResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyse_avgline_result
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int countByExample(TAnalyseAvglineResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyse_avgline_result
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int deleteByExample(TAnalyseAvglineResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyse_avgline_result
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyse_avgline_result
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int insert(TAnalyseAvglineResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyse_avgline_result
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int insertSelective(TAnalyseAvglineResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyse_avgline_result
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    List<TAnalyseAvglineResult> selectByExample(TAnalyseAvglineResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyse_avgline_result
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    TAnalyseAvglineResult selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyse_avgline_result
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") TAnalyseAvglineResult record, @Param("example") TAnalyseAvglineResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyse_avgline_result
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int updateByExample(@Param("record") TAnalyseAvglineResult record, @Param("example") TAnalyseAvglineResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyse_avgline_result
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int updateByPrimaryKeySelective(TAnalyseAvglineResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyse_avgline_result
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int updateByPrimaryKey(TAnalyseAvglineResult record);
}