package com.zsh.labouCapital.dao.client;

import com.zsh.labouCapital.dao.dto.TFundCompany;
import com.zsh.labouCapital.dao.dto.TFundCompanyCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TFundCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_company
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    int countByExample(TFundCompanyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_company
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    int deleteByExample(TFundCompanyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_company
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_company
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    int insert(TFundCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_company
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    int insertSelective(TFundCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_company
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    List<TFundCompany> selectByExample(TFundCompanyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_company
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    TFundCompany selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_company
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") TFundCompany record, @Param("example") TFundCompanyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_company
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    int updateByExample(@Param("record") TFundCompany record, @Param("example") TFundCompanyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_company
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    int updateByPrimaryKeySelective(TFundCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund_company
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    int updateByPrimaryKey(TFundCompany record);
}