package com.zsh.labouCapital.dao.client;

import com.zsh.labouCapital.dao.dto.THoldFund;
import com.zsh.labouCapital.dao.dto.THoldFundCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface THoldFundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    int countByExample(THoldFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    int deleteByExample(THoldFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    int insert(THoldFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    int insertSelective(THoldFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    List<THoldFund> selectByExample(THoldFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    THoldFund selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") THoldFund record, @Param("example") THoldFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    int updateByExample(@Param("record") THoldFund record, @Param("example") THoldFundCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    int updateByPrimaryKeySelective(THoldFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    int updateByPrimaryKey(THoldFund record);
}