package com.zsh.labouCapital.dao.client;

import com.zsh.labouCapital.dao.dto.THoldFundSummary;
import com.zsh.labouCapital.dao.dto.THoldFundSummaryCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface THoldFundSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund_summary
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int countByExample(THoldFundSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund_summary
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int deleteByExample(THoldFundSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund_summary
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund_summary
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int insert(THoldFundSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund_summary
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int insertSelective(THoldFundSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund_summary
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    List<THoldFundSummary> selectByExample(THoldFundSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund_summary
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    THoldFundSummary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund_summary
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") THoldFundSummary record, @Param("example") THoldFundSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund_summary
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int updateByExample(@Param("record") THoldFundSummary record, @Param("example") THoldFundSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund_summary
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int updateByPrimaryKeySelective(THoldFundSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund_summary
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int updateByPrimaryKey(THoldFundSummary record);
}