package com.zsh.labouCapital.dao.client;

import com.zsh.labouCapital.dao.dto.TNetWorthHistory;
import com.zsh.labouCapital.dao.dto.TNetWorthHistoryCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TNetWorthHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_history
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int countByExample(TNetWorthHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_history
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int deleteByExample(TNetWorthHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_history
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_history
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int insert(TNetWorthHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_history
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int insertSelective(TNetWorthHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_history
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    List<TNetWorthHistory> selectByExample(TNetWorthHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_history
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    TNetWorthHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_history
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") TNetWorthHistory record, @Param("example") TNetWorthHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_history
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int updateByExample(@Param("record") TNetWorthHistory record, @Param("example") TNetWorthHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_history
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int updateByPrimaryKeySelective(TNetWorthHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_history
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    int updateByPrimaryKey(TNetWorthHistory record);
}