package com.zsh.labouCapital.dao.client;

import com.zsh.labouCapital.dao.dto.TTest;
import com.zsh.labouCapital.dao.dto.TTestCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    int countByExample(TTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    int deleteByExample(TTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    int insert(TTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    int insertSelective(TTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    List<TTest> selectByExample(TTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    TTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") TTest record, @Param("example") TTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    int updateByExample(@Param("record") TTest record, @Param("example") TTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    int updateByPrimaryKeySelective(TTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    int updateByPrimaryKey(TTest record);
}