package com.zsh.labouCapital.dao.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TAvglineBugRecordCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    protected List<Criteria> oredCriteria;

    protected Integer limit;

    protected Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public TAvglineBugRecordCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return this.limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return this.offset;
    }

    public BoundBuilder boundBuilder() {
        return new BoundBuilder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNetWorthIdIsNull() {
            addCriterion("net_worth_id is null");
            return (Criteria) this;
        }

        public Criteria andNetWorthIdIsNotNull() {
            addCriterion("net_worth_id is not null");
            return (Criteria) this;
        }

        public Criteria andNetWorthIdEqualTo(String value) {
            addCriterion("net_worth_id =", value, "netWorthId");
            return (Criteria) this;
        }

        public Criteria andNetWorthIdNotEqualTo(String value) {
            addCriterion("net_worth_id <>", value, "netWorthId");
            return (Criteria) this;
        }

        public Criteria andNetWorthIdGreaterThan(String value) {
            addCriterion("net_worth_id >", value, "netWorthId");
            return (Criteria) this;
        }

        public Criteria andNetWorthIdGreaterThanOrEqualTo(String value) {
            addCriterion("net_worth_id >=", value, "netWorthId");
            return (Criteria) this;
        }

        public Criteria andNetWorthIdLessThan(String value) {
            addCriterion("net_worth_id <", value, "netWorthId");
            return (Criteria) this;
        }

        public Criteria andNetWorthIdLessThanOrEqualTo(String value) {
            addCriterion("net_worth_id <=", value, "netWorthId");
            return (Criteria) this;
        }

        public Criteria andNetWorthIdLike(String value) {
            addCriterion("net_worth_id like", value, "netWorthId");
            return (Criteria) this;
        }

        public Criteria andNetWorthIdNotLike(String value) {
            addCriterion("net_worth_id not like", value, "netWorthId");
            return (Criteria) this;
        }

        public Criteria andNetWorthIdIn(List<String> values) {
            addCriterion("net_worth_id in", values, "netWorthId");
            return (Criteria) this;
        }

        public Criteria andNetWorthIdNotIn(List<String> values) {
            addCriterion("net_worth_id not in", values, "netWorthId");
            return (Criteria) this;
        }

        public Criteria andNetWorthIdBetween(String value1, String value2) {
            addCriterion("net_worth_id between", value1, value2, "netWorthId");
            return (Criteria) this;
        }

        public Criteria andNetWorthIdNotBetween(String value1, String value2) {
            addCriterion("net_worth_id not between", value1, value2, "netWorthId");
            return (Criteria) this;
        }

        public Criteria andFundCodeIsNull() {
            addCriterion("fund_code is null");
            return (Criteria) this;
        }

        public Criteria andFundCodeIsNotNull() {
            addCriterion("fund_code is not null");
            return (Criteria) this;
        }

        public Criteria andFundCodeEqualTo(String value) {
            addCriterion("fund_code =", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotEqualTo(String value) {
            addCriterion("fund_code <>", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeGreaterThan(String value) {
            addCriterion("fund_code >", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeGreaterThanOrEqualTo(String value) {
            addCriterion("fund_code >=", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLessThan(String value) {
            addCriterion("fund_code <", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLessThanOrEqualTo(String value) {
            addCriterion("fund_code <=", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLike(String value) {
            addCriterion("fund_code like", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotLike(String value) {
            addCriterion("fund_code not like", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeIn(List<String> values) {
            addCriterion("fund_code in", values, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotIn(List<String> values) {
            addCriterion("fund_code not in", values, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeBetween(String value1, String value2) {
            addCriterion("fund_code between", value1, value2, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotBetween(String value1, String value2) {
            addCriterion("fund_code not between", value1, value2, "fundCode");
            return (Criteria) this;
        }

        public Criteria andDateInfoIsNull() {
            addCriterion("date_info is null");
            return (Criteria) this;
        }

        public Criteria andDateInfoIsNotNull() {
            addCriterion("date_info is not null");
            return (Criteria) this;
        }

        public Criteria andDateInfoEqualTo(Date value) {
            addCriterion("date_info =", value, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoNotEqualTo(Date value) {
            addCriterion("date_info <>", value, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoGreaterThan(Date value) {
            addCriterion("date_info >", value, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoGreaterThanOrEqualTo(Date value) {
            addCriterion("date_info >=", value, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoLessThan(Date value) {
            addCriterion("date_info <", value, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoLessThanOrEqualTo(Date value) {
            addCriterion("date_info <=", value, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoIn(List<Date> values) {
            addCriterion("date_info in", values, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoNotIn(List<Date> values) {
            addCriterion("date_info not in", values, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoBetween(Date value1, Date value2) {
            addCriterion("date_info between", value1, value2, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoNotBetween(Date value1, Date value2) {
            addCriterion("date_info not between", value1, value2, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andNetWorthIsNull() {
            addCriterion("net_worth is null");
            return (Criteria) this;
        }

        public Criteria andNetWorthIsNotNull() {
            addCriterion("net_worth is not null");
            return (Criteria) this;
        }

        public Criteria andNetWorthEqualTo(Double value) {
            addCriterion("net_worth =", value, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthNotEqualTo(Double value) {
            addCriterion("net_worth <>", value, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthGreaterThan(Double value) {
            addCriterion("net_worth >", value, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthGreaterThanOrEqualTo(Double value) {
            addCriterion("net_worth >=", value, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthLessThan(Double value) {
            addCriterion("net_worth <", value, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthLessThanOrEqualTo(Double value) {
            addCriterion("net_worth <=", value, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthIn(List<Double> values) {
            addCriterion("net_worth in", values, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthNotIn(List<Double> values) {
            addCriterion("net_worth not in", values, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthBetween(Double value1, Double value2) {
            addCriterion("net_worth between", value1, value2, "netWorth");
            return (Criteria) this;
        }

        public Criteria andNetWorthNotBetween(Double value1, Double value2) {
            addCriterion("net_worth not between", value1, value2, "netWorth");
            return (Criteria) this;
        }

        public Criteria andAvgLineWorthIsNull() {
            addCriterion("avg_line_worth is null");
            return (Criteria) this;
        }

        public Criteria andAvgLineWorthIsNotNull() {
            addCriterion("avg_line_worth is not null");
            return (Criteria) this;
        }

        public Criteria andAvgLineWorthEqualTo(Double value) {
            addCriterion("avg_line_worth =", value, "avgLineWorth");
            return (Criteria) this;
        }

        public Criteria andAvgLineWorthNotEqualTo(Double value) {
            addCriterion("avg_line_worth <>", value, "avgLineWorth");
            return (Criteria) this;
        }

        public Criteria andAvgLineWorthGreaterThan(Double value) {
            addCriterion("avg_line_worth >", value, "avgLineWorth");
            return (Criteria) this;
        }

        public Criteria andAvgLineWorthGreaterThanOrEqualTo(Double value) {
            addCriterion("avg_line_worth >=", value, "avgLineWorth");
            return (Criteria) this;
        }

        public Criteria andAvgLineWorthLessThan(Double value) {
            addCriterion("avg_line_worth <", value, "avgLineWorth");
            return (Criteria) this;
        }

        public Criteria andAvgLineWorthLessThanOrEqualTo(Double value) {
            addCriterion("avg_line_worth <=", value, "avgLineWorth");
            return (Criteria) this;
        }

        public Criteria andAvgLineWorthIn(List<Double> values) {
            addCriterion("avg_line_worth in", values, "avgLineWorth");
            return (Criteria) this;
        }

        public Criteria andAvgLineWorthNotIn(List<Double> values) {
            addCriterion("avg_line_worth not in", values, "avgLineWorth");
            return (Criteria) this;
        }

        public Criteria andAvgLineWorthBetween(Double value1, Double value2) {
            addCriterion("avg_line_worth between", value1, value2, "avgLineWorth");
            return (Criteria) this;
        }

        public Criteria andAvgLineWorthNotBetween(Double value1, Double value2) {
            addCriterion("avg_line_worth not between", value1, value2, "avgLineWorth");
            return (Criteria) this;
        }

        public Criteria andDiffValueIsNull() {
            addCriterion("diff_value is null");
            return (Criteria) this;
        }

        public Criteria andDiffValueIsNotNull() {
            addCriterion("diff_value is not null");
            return (Criteria) this;
        }

        public Criteria andDiffValueEqualTo(Double value) {
            addCriterion("diff_value =", value, "diffValue");
            return (Criteria) this;
        }

        public Criteria andDiffValueNotEqualTo(Double value) {
            addCriterion("diff_value <>", value, "diffValue");
            return (Criteria) this;
        }

        public Criteria andDiffValueGreaterThan(Double value) {
            addCriterion("diff_value >", value, "diffValue");
            return (Criteria) this;
        }

        public Criteria andDiffValueGreaterThanOrEqualTo(Double value) {
            addCriterion("diff_value >=", value, "diffValue");
            return (Criteria) this;
        }

        public Criteria andDiffValueLessThan(Double value) {
            addCriterion("diff_value <", value, "diffValue");
            return (Criteria) this;
        }

        public Criteria andDiffValueLessThanOrEqualTo(Double value) {
            addCriterion("diff_value <=", value, "diffValue");
            return (Criteria) this;
        }

        public Criteria andDiffValueIn(List<Double> values) {
            addCriterion("diff_value in", values, "diffValue");
            return (Criteria) this;
        }

        public Criteria andDiffValueNotIn(List<Double> values) {
            addCriterion("diff_value not in", values, "diffValue");
            return (Criteria) this;
        }

        public Criteria andDiffValueBetween(Double value1, Double value2) {
            addCriterion("diff_value between", value1, value2, "diffValue");
            return (Criteria) this;
        }

        public Criteria andDiffValueNotBetween(Double value1, Double value2) {
            addCriterion("diff_value not between", value1, value2, "diffValue");
            return (Criteria) this;
        }

        public Criteria andAvgLineTypeIsNull() {
            addCriterion("avg_line_type is null");
            return (Criteria) this;
        }

        public Criteria andAvgLineTypeIsNotNull() {
            addCriterion("avg_line_type is not null");
            return (Criteria) this;
        }

        public Criteria andAvgLineTypeEqualTo(Integer value) {
            addCriterion("avg_line_type =", value, "avgLineType");
            return (Criteria) this;
        }

        public Criteria andAvgLineTypeNotEqualTo(Integer value) {
            addCriterion("avg_line_type <>", value, "avgLineType");
            return (Criteria) this;
        }

        public Criteria andAvgLineTypeGreaterThan(Integer value) {
            addCriterion("avg_line_type >", value, "avgLineType");
            return (Criteria) this;
        }

        public Criteria andAvgLineTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("avg_line_type >=", value, "avgLineType");
            return (Criteria) this;
        }

        public Criteria andAvgLineTypeLessThan(Integer value) {
            addCriterion("avg_line_type <", value, "avgLineType");
            return (Criteria) this;
        }

        public Criteria andAvgLineTypeLessThanOrEqualTo(Integer value) {
            addCriterion("avg_line_type <=", value, "avgLineType");
            return (Criteria) this;
        }

        public Criteria andAvgLineTypeIn(List<Integer> values) {
            addCriterion("avg_line_type in", values, "avgLineType");
            return (Criteria) this;
        }

        public Criteria andAvgLineTypeNotIn(List<Integer> values) {
            addCriterion("avg_line_type not in", values, "avgLineType");
            return (Criteria) this;
        }

        public Criteria andAvgLineTypeBetween(Integer value1, Integer value2) {
            addCriterion("avg_line_type between", value1, value2, "avgLineType");
            return (Criteria) this;
        }

        public Criteria andAvgLineTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("avg_line_type not between", value1, value2, "avgLineType");
            return (Criteria) this;
        }

        public Criteria andBugMoneyIsNull() {
            addCriterion("bug_money is null");
            return (Criteria) this;
        }

        public Criteria andBugMoneyIsNotNull() {
            addCriterion("bug_money is not null");
            return (Criteria) this;
        }

        public Criteria andBugMoneyEqualTo(Double value) {
            addCriterion("bug_money =", value, "bugMoney");
            return (Criteria) this;
        }

        public Criteria andBugMoneyNotEqualTo(Double value) {
            addCriterion("bug_money <>", value, "bugMoney");
            return (Criteria) this;
        }

        public Criteria andBugMoneyGreaterThan(Double value) {
            addCriterion("bug_money >", value, "bugMoney");
            return (Criteria) this;
        }

        public Criteria andBugMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("bug_money >=", value, "bugMoney");
            return (Criteria) this;
        }

        public Criteria andBugMoneyLessThan(Double value) {
            addCriterion("bug_money <", value, "bugMoney");
            return (Criteria) this;
        }

        public Criteria andBugMoneyLessThanOrEqualTo(Double value) {
            addCriterion("bug_money <=", value, "bugMoney");
            return (Criteria) this;
        }

        public Criteria andBugMoneyIn(List<Double> values) {
            addCriterion("bug_money in", values, "bugMoney");
            return (Criteria) this;
        }

        public Criteria andBugMoneyNotIn(List<Double> values) {
            addCriterion("bug_money not in", values, "bugMoney");
            return (Criteria) this;
        }

        public Criteria andBugMoneyBetween(Double value1, Double value2) {
            addCriterion("bug_money between", value1, value2, "bugMoney");
            return (Criteria) this;
        }

        public Criteria andBugMoneyNotBetween(Double value1, Double value2) {
            addCriterion("bug_money not between", value1, value2, "bugMoney");
            return (Criteria) this;
        }

        public Criteria andBugNumIsNull() {
            addCriterion("bug_num is null");
            return (Criteria) this;
        }

        public Criteria andBugNumIsNotNull() {
            addCriterion("bug_num is not null");
            return (Criteria) this;
        }

        public Criteria andBugNumEqualTo(Double value) {
            addCriterion("bug_num =", value, "bugNum");
            return (Criteria) this;
        }

        public Criteria andBugNumNotEqualTo(Double value) {
            addCriterion("bug_num <>", value, "bugNum");
            return (Criteria) this;
        }

        public Criteria andBugNumGreaterThan(Double value) {
            addCriterion("bug_num >", value, "bugNum");
            return (Criteria) this;
        }

        public Criteria andBugNumGreaterThanOrEqualTo(Double value) {
            addCriterion("bug_num >=", value, "bugNum");
            return (Criteria) this;
        }

        public Criteria andBugNumLessThan(Double value) {
            addCriterion("bug_num <", value, "bugNum");
            return (Criteria) this;
        }

        public Criteria andBugNumLessThanOrEqualTo(Double value) {
            addCriterion("bug_num <=", value, "bugNum");
            return (Criteria) this;
        }

        public Criteria andBugNumIn(List<Double> values) {
            addCriterion("bug_num in", values, "bugNum");
            return (Criteria) this;
        }

        public Criteria andBugNumNotIn(List<Double> values) {
            addCriterion("bug_num not in", values, "bugNum");
            return (Criteria) this;
        }

        public Criteria andBugNumBetween(Double value1, Double value2) {
            addCriterion("bug_num between", value1, value2, "bugNum");
            return (Criteria) this;
        }

        public Criteria andBugNumNotBetween(Double value1, Double value2) {
            addCriterion("bug_num not between", value1, value2, "bugNum");
            return (Criteria) this;
        }

        public Criteria andBugCostIsNull() {
            addCriterion("bug_cost is null");
            return (Criteria) this;
        }

        public Criteria andBugCostIsNotNull() {
            addCriterion("bug_cost is not null");
            return (Criteria) this;
        }

        public Criteria andBugCostEqualTo(Double value) {
            addCriterion("bug_cost =", value, "bugCost");
            return (Criteria) this;
        }

        public Criteria andBugCostNotEqualTo(Double value) {
            addCriterion("bug_cost <>", value, "bugCost");
            return (Criteria) this;
        }

        public Criteria andBugCostGreaterThan(Double value) {
            addCriterion("bug_cost >", value, "bugCost");
            return (Criteria) this;
        }

        public Criteria andBugCostGreaterThanOrEqualTo(Double value) {
            addCriterion("bug_cost >=", value, "bugCost");
            return (Criteria) this;
        }

        public Criteria andBugCostLessThan(Double value) {
            addCriterion("bug_cost <", value, "bugCost");
            return (Criteria) this;
        }

        public Criteria andBugCostLessThanOrEqualTo(Double value) {
            addCriterion("bug_cost <=", value, "bugCost");
            return (Criteria) this;
        }

        public Criteria andBugCostIn(List<Double> values) {
            addCriterion("bug_cost in", values, "bugCost");
            return (Criteria) this;
        }

        public Criteria andBugCostNotIn(List<Double> values) {
            addCriterion("bug_cost not in", values, "bugCost");
            return (Criteria) this;
        }

        public Criteria andBugCostBetween(Double value1, Double value2) {
            addCriterion("bug_cost between", value1, value2, "bugCost");
            return (Criteria) this;
        }

        public Criteria andBugCostNotBetween(Double value1, Double value2) {
            addCriterion("bug_cost not between", value1, value2, "bugCost");
            return (Criteria) this;
        }

        public Criteria andBuyModelIsNull() {
            addCriterion("buy_model is null");
            return (Criteria) this;
        }

        public Criteria andBuyModelIsNotNull() {
            addCriterion("buy_model is not null");
            return (Criteria) this;
        }

        public Criteria andBuyModelEqualTo(Integer value) {
            addCriterion("buy_model =", value, "buyModel");
            return (Criteria) this;
        }

        public Criteria andBuyModelNotEqualTo(Integer value) {
            addCriterion("buy_model <>", value, "buyModel");
            return (Criteria) this;
        }

        public Criteria andBuyModelGreaterThan(Integer value) {
            addCriterion("buy_model >", value, "buyModel");
            return (Criteria) this;
        }

        public Criteria andBuyModelGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_model >=", value, "buyModel");
            return (Criteria) this;
        }

        public Criteria andBuyModelLessThan(Integer value) {
            addCriterion("buy_model <", value, "buyModel");
            return (Criteria) this;
        }

        public Criteria andBuyModelLessThanOrEqualTo(Integer value) {
            addCriterion("buy_model <=", value, "buyModel");
            return (Criteria) this;
        }

        public Criteria andBuyModelIn(List<Integer> values) {
            addCriterion("buy_model in", values, "buyModel");
            return (Criteria) this;
        }

        public Criteria andBuyModelNotIn(List<Integer> values) {
            addCriterion("buy_model not in", values, "buyModel");
            return (Criteria) this;
        }

        public Criteria andBuyModelBetween(Integer value1, Integer value2) {
            addCriterion("buy_model between", value1, value2, "buyModel");
            return (Criteria) this;
        }

        public Criteria andBuyModelNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_model not between", value1, value2, "buyModel");
            return (Criteria) this;
        }

        public Criteria andDateCreateIsNull() {
            addCriterion("date_create is null");
            return (Criteria) this;
        }

        public Criteria andDateCreateIsNotNull() {
            addCriterion("date_create is not null");
            return (Criteria) this;
        }

        public Criteria andDateCreateEqualTo(Date value) {
            addCriterion("date_create =", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateNotEqualTo(Date value) {
            addCriterion("date_create <>", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateGreaterThan(Date value) {
            addCriterion("date_create >", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("date_create >=", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateLessThan(Date value) {
            addCriterion("date_create <", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateLessThanOrEqualTo(Date value) {
            addCriterion("date_create <=", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateIn(List<Date> values) {
            addCriterion("date_create in", values, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateNotIn(List<Date> values) {
            addCriterion("date_create not in", values, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateBetween(Date value1, Date value2) {
            addCriterion("date_create between", value1, value2, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateNotBetween(Date value1, Date value2) {
            addCriterion("date_create not between", value1, value2, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterion("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterion("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterion("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterion("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterion("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterion("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterion("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterion("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterion("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("end_date is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterion("end_date =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterion("end_date <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterion("end_date >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("end_date >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterion("end_date <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterion("end_date <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterion("end_date in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterion("end_date not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterion("end_date between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterion("end_date not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andBatchNoIsNull() {
            addCriterion("batch_no is null");
            return (Criteria) this;
        }

        public Criteria andBatchNoIsNotNull() {
            addCriterion("batch_no is not null");
            return (Criteria) this;
        }

        public Criteria andBatchNoEqualTo(String value) {
            addCriterion("batch_no =", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotEqualTo(String value) {
            addCriterion("batch_no <>", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoGreaterThan(String value) {
            addCriterion("batch_no >", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoGreaterThanOrEqualTo(String value) {
            addCriterion("batch_no >=", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoLessThan(String value) {
            addCriterion("batch_no <", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoLessThanOrEqualTo(String value) {
            addCriterion("batch_no <=", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoLike(String value) {
            addCriterion("batch_no like", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotLike(String value) {
            addCriterion("batch_no not like", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoIn(List<String> values) {
            addCriterion("batch_no in", values, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotIn(List<String> values) {
            addCriterion("batch_no not in", values, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoBetween(String value1, String value2) {
            addCriterion("batch_no between", value1, value2, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotBetween(String value1, String value2) {
            addCriterion("batch_no not between", value1, value2, "batchNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated do_not_delete_during_merge Fri Oct 11 17:37:08 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_avgline_bug_record
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public class BoundBuilder {
        protected Integer limit;

        protected Integer offset;

        public Integer limit() {
            return this.limit;
        }

        public BoundBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }

        public Integer offset() {
            return this.offset;
        }

        public BoundBuilder offset(Integer offset) {
            this.offset = offset;
            return this;
        }

        public TAvglineBugRecordCriteria build() {
            TAvglineBugRecordCriteria.this.limit = limit;
            TAvglineBugRecordCriteria.this.offset = offset;
            return TAvglineBugRecordCriteria.this;
        }
    }
}