package com.zsh.labouCapital.dao.dto;

import java.io.Serializable;
import java.util.Date;

public class TFund implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.fund_code
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String fundCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.index_code
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String indexCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.fund_name
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String fundName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.buy_status
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private Integer buyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.redemption_status
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private Integer redemptionStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.poundage
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private Double poundage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.fund_type
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private Integer fundType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.trace_type
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private Integer traceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.trace_target
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private Integer traceTarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.index_id
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private Long indexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.detail_url
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String detailUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.fund_scale
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String fundScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.fund_manager
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String fundManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.establish_date
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String establishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.company_name
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.trace_error
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String traceError;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.grade
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.risk
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String risk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.type2
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String type2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.company_code
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.history_url
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String historyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.guzhi_url
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private String guzhiUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.is_except
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private Integer isExcept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.date_created
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fund.date_updated
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private Date dateUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fund
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.fund_code
     *
     * @return the value of t_fund.fund_code
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.fund_code
     *
     * @param fundCode the value for t_fund.fund_code
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode == null ? null : fundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.index_code
     *
     * @return the value of t_fund.index_code
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getIndexCode() {
        return indexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.index_code
     *
     * @param indexCode the value for t_fund.index_code
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setIndexCode(String indexCode) {
        this.indexCode = indexCode == null ? null : indexCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.fund_name
     *
     * @return the value of t_fund.fund_name
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.fund_name
     *
     * @param fundName the value for t_fund.fund_name
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setFundName(String fundName) {
        this.fundName = fundName == null ? null : fundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.buy_status
     *
     * @return the value of t_fund.buy_status
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public Integer getBuyStatus() {
        return buyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.buy_status
     *
     * @param buyStatus the value for t_fund.buy_status
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setBuyStatus(Integer buyStatus) {
        this.buyStatus = buyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.redemption_status
     *
     * @return the value of t_fund.redemption_status
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public Integer getRedemptionStatus() {
        return redemptionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.redemption_status
     *
     * @param redemptionStatus the value for t_fund.redemption_status
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setRedemptionStatus(Integer redemptionStatus) {
        this.redemptionStatus = redemptionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.poundage
     *
     * @return the value of t_fund.poundage
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public Double getPoundage() {
        return poundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.poundage
     *
     * @param poundage the value for t_fund.poundage
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setPoundage(Double poundage) {
        this.poundage = poundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.fund_type
     *
     * @return the value of t_fund.fund_type
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public Integer getFundType() {
        return fundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.fund_type
     *
     * @param fundType the value for t_fund.fund_type
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setFundType(Integer fundType) {
        this.fundType = fundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.trace_type
     *
     * @return the value of t_fund.trace_type
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public Integer getTraceType() {
        return traceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.trace_type
     *
     * @param traceType the value for t_fund.trace_type
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setTraceType(Integer traceType) {
        this.traceType = traceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.trace_target
     *
     * @return the value of t_fund.trace_target
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public Integer getTraceTarget() {
        return traceTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.trace_target
     *
     * @param traceTarget the value for t_fund.trace_target
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setTraceTarget(Integer traceTarget) {
        this.traceTarget = traceTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.index_id
     *
     * @return the value of t_fund.index_id
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public Long getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.index_id
     *
     * @param indexId the value for t_fund.index_id
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setIndexId(Long indexId) {
        this.indexId = indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.detail_url
     *
     * @return the value of t_fund.detail_url
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getDetailUrl() {
        return detailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.detail_url
     *
     * @param detailUrl the value for t_fund.detail_url
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setDetailUrl(String detailUrl) {
        this.detailUrl = detailUrl == null ? null : detailUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.fund_scale
     *
     * @return the value of t_fund.fund_scale
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getFundScale() {
        return fundScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.fund_scale
     *
     * @param fundScale the value for t_fund.fund_scale
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setFundScale(String fundScale) {
        this.fundScale = fundScale == null ? null : fundScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.fund_manager
     *
     * @return the value of t_fund.fund_manager
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getFundManager() {
        return fundManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.fund_manager
     *
     * @param fundManager the value for t_fund.fund_manager
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setFundManager(String fundManager) {
        this.fundManager = fundManager == null ? null : fundManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.establish_date
     *
     * @return the value of t_fund.establish_date
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getEstablishDate() {
        return establishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.establish_date
     *
     * @param establishDate the value for t_fund.establish_date
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setEstablishDate(String establishDate) {
        this.establishDate = establishDate == null ? null : establishDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.company_name
     *
     * @return the value of t_fund.company_name
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.company_name
     *
     * @param companyName the value for t_fund.company_name
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.trace_error
     *
     * @return the value of t_fund.trace_error
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getTraceError() {
        return traceError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.trace_error
     *
     * @param traceError the value for t_fund.trace_error
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setTraceError(String traceError) {
        this.traceError = traceError == null ? null : traceError.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.grade
     *
     * @return the value of t_fund.grade
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.grade
     *
     * @param grade the value for t_fund.grade
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.risk
     *
     * @return the value of t_fund.risk
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getRisk() {
        return risk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.risk
     *
     * @param risk the value for t_fund.risk
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setRisk(String risk) {
        this.risk = risk == null ? null : risk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.type2
     *
     * @return the value of t_fund.type2
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getType2() {
        return type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.type2
     *
     * @param type2 the value for t_fund.type2
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setType2(String type2) {
        this.type2 = type2 == null ? null : type2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.company_code
     *
     * @return the value of t_fund.company_code
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.company_code
     *
     * @param companyCode the value for t_fund.company_code
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.history_url
     *
     * @return the value of t_fund.history_url
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getHistoryUrl() {
        return historyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.history_url
     *
     * @param historyUrl the value for t_fund.history_url
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setHistoryUrl(String historyUrl) {
        this.historyUrl = historyUrl == null ? null : historyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.guzhi_url
     *
     * @return the value of t_fund.guzhi_url
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public String getGuzhiUrl() {
        return guzhiUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.guzhi_url
     *
     * @param guzhiUrl the value for t_fund.guzhi_url
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setGuzhiUrl(String guzhiUrl) {
        this.guzhiUrl = guzhiUrl == null ? null : guzhiUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.is_except
     *
     * @return the value of t_fund.is_except
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public Integer getIsExcept() {
        return isExcept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.is_except
     *
     * @param isExcept the value for t_fund.is_except
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setIsExcept(Integer isExcept) {
        this.isExcept = isExcept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.date_created
     *
     * @return the value of t_fund.date_created
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.date_created
     *
     * @param dateCreated the value for t_fund.date_created
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fund.date_updated
     *
     * @return the value of t_fund.date_updated
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public Date getDateUpdated() {
        return dateUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fund.date_updated
     *
     * @param dateUpdated the value for t_fund.date_updated
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fund
     *
     * @mbggenerated Fri Oct 11 17:37:08 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fundCode=").append(fundCode);
        sb.append(", indexCode=").append(indexCode);
        sb.append(", fundName=").append(fundName);
        sb.append(", buyStatus=").append(buyStatus);
        sb.append(", redemptionStatus=").append(redemptionStatus);
        sb.append(", poundage=").append(poundage);
        sb.append(", fundType=").append(fundType);
        sb.append(", traceType=").append(traceType);
        sb.append(", traceTarget=").append(traceTarget);
        sb.append(", indexId=").append(indexId);
        sb.append(", detailUrl=").append(detailUrl);
        sb.append(", fundScale=").append(fundScale);
        sb.append(", fundManager=").append(fundManager);
        sb.append(", establishDate=").append(establishDate);
        sb.append(", companyName=").append(companyName);
        sb.append(", traceError=").append(traceError);
        sb.append(", grade=").append(grade);
        sb.append(", risk=").append(risk);
        sb.append(", type2=").append(type2);
        sb.append(", companyCode=").append(companyCode);
        sb.append(", historyUrl=").append(historyUrl);
        sb.append(", guzhiUrl=").append(guzhiUrl);
        sb.append(", isExcept=").append(isExcept);
        sb.append(", dateCreated=").append(dateCreated);
        sb.append(", dateUpdated=").append(dateUpdated);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}