package com.zsh.labouCapital.dao.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class THoldFundCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    protected List<Criteria> oredCriteria;

    protected Integer limit;

    protected Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    public THoldFundCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return this.limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return this.offset;
    }

    public BoundBuilder boundBuilder() {
        return new BoundBuilder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFundCodeIsNull() {
            addCriterion("fund_code is null");
            return (Criteria) this;
        }

        public Criteria andFundCodeIsNotNull() {
            addCriterion("fund_code is not null");
            return (Criteria) this;
        }

        public Criteria andFundCodeEqualTo(String value) {
            addCriterion("fund_code =", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotEqualTo(String value) {
            addCriterion("fund_code <>", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeGreaterThan(String value) {
            addCriterion("fund_code >", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeGreaterThanOrEqualTo(String value) {
            addCriterion("fund_code >=", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLessThan(String value) {
            addCriterion("fund_code <", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLessThanOrEqualTo(String value) {
            addCriterion("fund_code <=", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLike(String value) {
            addCriterion("fund_code like", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotLike(String value) {
            addCriterion("fund_code not like", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeIn(List<String> values) {
            addCriterion("fund_code in", values, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotIn(List<String> values) {
            addCriterion("fund_code not in", values, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeBetween(String value1, String value2) {
            addCriterion("fund_code between", value1, value2, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotBetween(String value1, String value2) {
            addCriterion("fund_code not between", value1, value2, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundNameIsNull() {
            addCriterion("fund_name is null");
            return (Criteria) this;
        }

        public Criteria andFundNameIsNotNull() {
            addCriterion("fund_name is not null");
            return (Criteria) this;
        }

        public Criteria andFundNameEqualTo(String value) {
            addCriterion("fund_name =", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameNotEqualTo(String value) {
            addCriterion("fund_name <>", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameGreaterThan(String value) {
            addCriterion("fund_name >", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameGreaterThanOrEqualTo(String value) {
            addCriterion("fund_name >=", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameLessThan(String value) {
            addCriterion("fund_name <", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameLessThanOrEqualTo(String value) {
            addCriterion("fund_name <=", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameLike(String value) {
            addCriterion("fund_name like", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameNotLike(String value) {
            addCriterion("fund_name not like", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameIn(List<String> values) {
            addCriterion("fund_name in", values, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameNotIn(List<String> values) {
            addCriterion("fund_name not in", values, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameBetween(String value1, String value2) {
            addCriterion("fund_name between", value1, value2, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameNotBetween(String value1, String value2) {
            addCriterion("fund_name not between", value1, value2, "fundName");
            return (Criteria) this;
        }

        public Criteria andHoldCostIsNull() {
            addCriterion("hold_cost is null");
            return (Criteria) this;
        }

        public Criteria andHoldCostIsNotNull() {
            addCriterion("hold_cost is not null");
            return (Criteria) this;
        }

        public Criteria andHoldCostEqualTo(Double value) {
            addCriterion("hold_cost =", value, "holdCost");
            return (Criteria) this;
        }

        public Criteria andHoldCostNotEqualTo(Double value) {
            addCriterion("hold_cost <>", value, "holdCost");
            return (Criteria) this;
        }

        public Criteria andHoldCostGreaterThan(Double value) {
            addCriterion("hold_cost >", value, "holdCost");
            return (Criteria) this;
        }

        public Criteria andHoldCostGreaterThanOrEqualTo(Double value) {
            addCriterion("hold_cost >=", value, "holdCost");
            return (Criteria) this;
        }

        public Criteria andHoldCostLessThan(Double value) {
            addCriterion("hold_cost <", value, "holdCost");
            return (Criteria) this;
        }

        public Criteria andHoldCostLessThanOrEqualTo(Double value) {
            addCriterion("hold_cost <=", value, "holdCost");
            return (Criteria) this;
        }

        public Criteria andHoldCostIn(List<Double> values) {
            addCriterion("hold_cost in", values, "holdCost");
            return (Criteria) this;
        }

        public Criteria andHoldCostNotIn(List<Double> values) {
            addCriterion("hold_cost not in", values, "holdCost");
            return (Criteria) this;
        }

        public Criteria andHoldCostBetween(Double value1, Double value2) {
            addCriterion("hold_cost between", value1, value2, "holdCost");
            return (Criteria) this;
        }

        public Criteria andHoldCostNotBetween(Double value1, Double value2) {
            addCriterion("hold_cost not between", value1, value2, "holdCost");
            return (Criteria) this;
        }

        public Criteria andAccumCostIsNull() {
            addCriterion("accum_cost is null");
            return (Criteria) this;
        }

        public Criteria andAccumCostIsNotNull() {
            addCriterion("accum_cost is not null");
            return (Criteria) this;
        }

        public Criteria andAccumCostEqualTo(Double value) {
            addCriterion("accum_cost =", value, "accumCost");
            return (Criteria) this;
        }

        public Criteria andAccumCostNotEqualTo(Double value) {
            addCriterion("accum_cost <>", value, "accumCost");
            return (Criteria) this;
        }

        public Criteria andAccumCostGreaterThan(Double value) {
            addCriterion("accum_cost >", value, "accumCost");
            return (Criteria) this;
        }

        public Criteria andAccumCostGreaterThanOrEqualTo(Double value) {
            addCriterion("accum_cost >=", value, "accumCost");
            return (Criteria) this;
        }

        public Criteria andAccumCostLessThan(Double value) {
            addCriterion("accum_cost <", value, "accumCost");
            return (Criteria) this;
        }

        public Criteria andAccumCostLessThanOrEqualTo(Double value) {
            addCriterion("accum_cost <=", value, "accumCost");
            return (Criteria) this;
        }

        public Criteria andAccumCostIn(List<Double> values) {
            addCriterion("accum_cost in", values, "accumCost");
            return (Criteria) this;
        }

        public Criteria andAccumCostNotIn(List<Double> values) {
            addCriterion("accum_cost not in", values, "accumCost");
            return (Criteria) this;
        }

        public Criteria andAccumCostBetween(Double value1, Double value2) {
            addCriterion("accum_cost between", value1, value2, "accumCost");
            return (Criteria) this;
        }

        public Criteria andAccumCostNotBetween(Double value1, Double value2) {
            addCriterion("accum_cost not between", value1, value2, "accumCost");
            return (Criteria) this;
        }

        public Criteria andMarketValueIsNull() {
            addCriterion("market_value is null");
            return (Criteria) this;
        }

        public Criteria andMarketValueIsNotNull() {
            addCriterion("market_value is not null");
            return (Criteria) this;
        }

        public Criteria andMarketValueEqualTo(Double value) {
            addCriterion("market_value =", value, "marketValue");
            return (Criteria) this;
        }

        public Criteria andMarketValueNotEqualTo(Double value) {
            addCriterion("market_value <>", value, "marketValue");
            return (Criteria) this;
        }

        public Criteria andMarketValueGreaterThan(Double value) {
            addCriterion("market_value >", value, "marketValue");
            return (Criteria) this;
        }

        public Criteria andMarketValueGreaterThanOrEqualTo(Double value) {
            addCriterion("market_value >=", value, "marketValue");
            return (Criteria) this;
        }

        public Criteria andMarketValueLessThan(Double value) {
            addCriterion("market_value <", value, "marketValue");
            return (Criteria) this;
        }

        public Criteria andMarketValueLessThanOrEqualTo(Double value) {
            addCriterion("market_value <=", value, "marketValue");
            return (Criteria) this;
        }

        public Criteria andMarketValueIn(List<Double> values) {
            addCriterion("market_value in", values, "marketValue");
            return (Criteria) this;
        }

        public Criteria andMarketValueNotIn(List<Double> values) {
            addCriterion("market_value not in", values, "marketValue");
            return (Criteria) this;
        }

        public Criteria andMarketValueBetween(Double value1, Double value2) {
            addCriterion("market_value between", value1, value2, "marketValue");
            return (Criteria) this;
        }

        public Criteria andMarketValueNotBetween(Double value1, Double value2) {
            addCriterion("market_value not between", value1, value2, "marketValue");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNull() {
            addCriterion("volume is null");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNotNull() {
            addCriterion("volume is not null");
            return (Criteria) this;
        }

        public Criteria andVolumeEqualTo(Double value) {
            addCriterion("volume =", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotEqualTo(Double value) {
            addCriterion("volume <>", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThan(Double value) {
            addCriterion("volume >", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThanOrEqualTo(Double value) {
            addCriterion("volume >=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThan(Double value) {
            addCriterion("volume <", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThanOrEqualTo(Double value) {
            addCriterion("volume <=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeIn(List<Double> values) {
            addCriterion("volume in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotIn(List<Double> values) {
            addCriterion("volume not in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeBetween(Double value1, Double value2) {
            addCriterion("volume between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotBetween(Double value1, Double value2) {
            addCriterion("volume not between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andTotalGainIsNull() {
            addCriterion("total_gain is null");
            return (Criteria) this;
        }

        public Criteria andTotalGainIsNotNull() {
            addCriterion("total_gain is not null");
            return (Criteria) this;
        }

        public Criteria andTotalGainEqualTo(Double value) {
            addCriterion("total_gain =", value, "totalGain");
            return (Criteria) this;
        }

        public Criteria andTotalGainNotEqualTo(Double value) {
            addCriterion("total_gain <>", value, "totalGain");
            return (Criteria) this;
        }

        public Criteria andTotalGainGreaterThan(Double value) {
            addCriterion("total_gain >", value, "totalGain");
            return (Criteria) this;
        }

        public Criteria andTotalGainGreaterThanOrEqualTo(Double value) {
            addCriterion("total_gain >=", value, "totalGain");
            return (Criteria) this;
        }

        public Criteria andTotalGainLessThan(Double value) {
            addCriterion("total_gain <", value, "totalGain");
            return (Criteria) this;
        }

        public Criteria andTotalGainLessThanOrEqualTo(Double value) {
            addCriterion("total_gain <=", value, "totalGain");
            return (Criteria) this;
        }

        public Criteria andTotalGainIn(List<Double> values) {
            addCriterion("total_gain in", values, "totalGain");
            return (Criteria) this;
        }

        public Criteria andTotalGainNotIn(List<Double> values) {
            addCriterion("total_gain not in", values, "totalGain");
            return (Criteria) this;
        }

        public Criteria andTotalGainBetween(Double value1, Double value2) {
            addCriterion("total_gain between", value1, value2, "totalGain");
            return (Criteria) this;
        }

        public Criteria andTotalGainNotBetween(Double value1, Double value2) {
            addCriterion("total_gain not between", value1, value2, "totalGain");
            return (Criteria) this;
        }

        public Criteria andHoldGainIsNull() {
            addCriterion("hold_gain is null");
            return (Criteria) this;
        }

        public Criteria andHoldGainIsNotNull() {
            addCriterion("hold_gain is not null");
            return (Criteria) this;
        }

        public Criteria andHoldGainEqualTo(Double value) {
            addCriterion("hold_gain =", value, "holdGain");
            return (Criteria) this;
        }

        public Criteria andHoldGainNotEqualTo(Double value) {
            addCriterion("hold_gain <>", value, "holdGain");
            return (Criteria) this;
        }

        public Criteria andHoldGainGreaterThan(Double value) {
            addCriterion("hold_gain >", value, "holdGain");
            return (Criteria) this;
        }

        public Criteria andHoldGainGreaterThanOrEqualTo(Double value) {
            addCriterion("hold_gain >=", value, "holdGain");
            return (Criteria) this;
        }

        public Criteria andHoldGainLessThan(Double value) {
            addCriterion("hold_gain <", value, "holdGain");
            return (Criteria) this;
        }

        public Criteria andHoldGainLessThanOrEqualTo(Double value) {
            addCriterion("hold_gain <=", value, "holdGain");
            return (Criteria) this;
        }

        public Criteria andHoldGainIn(List<Double> values) {
            addCriterion("hold_gain in", values, "holdGain");
            return (Criteria) this;
        }

        public Criteria andHoldGainNotIn(List<Double> values) {
            addCriterion("hold_gain not in", values, "holdGain");
            return (Criteria) this;
        }

        public Criteria andHoldGainBetween(Double value1, Double value2) {
            addCriterion("hold_gain between", value1, value2, "holdGain");
            return (Criteria) this;
        }

        public Criteria andHoldGainNotBetween(Double value1, Double value2) {
            addCriterion("hold_gain not between", value1, value2, "holdGain");
            return (Criteria) this;
        }

        public Criteria andDailyGainIsNull() {
            addCriterion("daily_gain is null");
            return (Criteria) this;
        }

        public Criteria andDailyGainIsNotNull() {
            addCriterion("daily_gain is not null");
            return (Criteria) this;
        }

        public Criteria andDailyGainEqualTo(Double value) {
            addCriterion("daily_gain =", value, "dailyGain");
            return (Criteria) this;
        }

        public Criteria andDailyGainNotEqualTo(Double value) {
            addCriterion("daily_gain <>", value, "dailyGain");
            return (Criteria) this;
        }

        public Criteria andDailyGainGreaterThan(Double value) {
            addCriterion("daily_gain >", value, "dailyGain");
            return (Criteria) this;
        }

        public Criteria andDailyGainGreaterThanOrEqualTo(Double value) {
            addCriterion("daily_gain >=", value, "dailyGain");
            return (Criteria) this;
        }

        public Criteria andDailyGainLessThan(Double value) {
            addCriterion("daily_gain <", value, "dailyGain");
            return (Criteria) this;
        }

        public Criteria andDailyGainLessThanOrEqualTo(Double value) {
            addCriterion("daily_gain <=", value, "dailyGain");
            return (Criteria) this;
        }

        public Criteria andDailyGainIn(List<Double> values) {
            addCriterion("daily_gain in", values, "dailyGain");
            return (Criteria) this;
        }

        public Criteria andDailyGainNotIn(List<Double> values) {
            addCriterion("daily_gain not in", values, "dailyGain");
            return (Criteria) this;
        }

        public Criteria andDailyGainBetween(Double value1, Double value2) {
            addCriterion("daily_gain between", value1, value2, "dailyGain");
            return (Criteria) this;
        }

        public Criteria andDailyGainNotBetween(Double value1, Double value2) {
            addCriterion("daily_gain not between", value1, value2, "dailyGain");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedAmountIsNull() {
            addCriterion("unconfirmed_amount is null");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedAmountIsNotNull() {
            addCriterion("unconfirmed_amount is not null");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedAmountEqualTo(Double value) {
            addCriterion("unconfirmed_amount =", value, "unconfirmedAmount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedAmountNotEqualTo(Double value) {
            addCriterion("unconfirmed_amount <>", value, "unconfirmedAmount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedAmountGreaterThan(Double value) {
            addCriterion("unconfirmed_amount >", value, "unconfirmedAmount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("unconfirmed_amount >=", value, "unconfirmedAmount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedAmountLessThan(Double value) {
            addCriterion("unconfirmed_amount <", value, "unconfirmedAmount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedAmountLessThanOrEqualTo(Double value) {
            addCriterion("unconfirmed_amount <=", value, "unconfirmedAmount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedAmountIn(List<Double> values) {
            addCriterion("unconfirmed_amount in", values, "unconfirmedAmount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedAmountNotIn(List<Double> values) {
            addCriterion("unconfirmed_amount not in", values, "unconfirmedAmount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedAmountBetween(Double value1, Double value2) {
            addCriterion("unconfirmed_amount between", value1, value2, "unconfirmedAmount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedAmountNotBetween(Double value1, Double value2) {
            addCriterion("unconfirmed_amount not between", value1, value2, "unconfirmedAmount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedVolumeIsNull() {
            addCriterion("unconfirmed_volume is null");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedVolumeIsNotNull() {
            addCriterion("unconfirmed_volume is not null");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedVolumeEqualTo(Double value) {
            addCriterion("unconfirmed_volume =", value, "unconfirmedVolume");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedVolumeNotEqualTo(Double value) {
            addCriterion("unconfirmed_volume <>", value, "unconfirmedVolume");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedVolumeGreaterThan(Double value) {
            addCriterion("unconfirmed_volume >", value, "unconfirmedVolume");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedVolumeGreaterThanOrEqualTo(Double value) {
            addCriterion("unconfirmed_volume >=", value, "unconfirmedVolume");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedVolumeLessThan(Double value) {
            addCriterion("unconfirmed_volume <", value, "unconfirmedVolume");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedVolumeLessThanOrEqualTo(Double value) {
            addCriterion("unconfirmed_volume <=", value, "unconfirmedVolume");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedVolumeIn(List<Double> values) {
            addCriterion("unconfirmed_volume in", values, "unconfirmedVolume");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedVolumeNotIn(List<Double> values) {
            addCriterion("unconfirmed_volume not in", values, "unconfirmedVolume");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedVolumeBetween(Double value1, Double value2) {
            addCriterion("unconfirmed_volume between", value1, value2, "unconfirmedVolume");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedVolumeNotBetween(Double value1, Double value2) {
            addCriterion("unconfirmed_volume not between", value1, value2, "unconfirmedVolume");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedCountIsNull() {
            addCriterion("unconfirmed_count is null");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedCountIsNotNull() {
            addCriterion("unconfirmed_count is not null");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedCountEqualTo(Double value) {
            addCriterion("unconfirmed_count =", value, "unconfirmedCount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedCountNotEqualTo(Double value) {
            addCriterion("unconfirmed_count <>", value, "unconfirmedCount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedCountGreaterThan(Double value) {
            addCriterion("unconfirmed_count >", value, "unconfirmedCount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedCountGreaterThanOrEqualTo(Double value) {
            addCriterion("unconfirmed_count >=", value, "unconfirmedCount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedCountLessThan(Double value) {
            addCriterion("unconfirmed_count <", value, "unconfirmedCount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedCountLessThanOrEqualTo(Double value) {
            addCriterion("unconfirmed_count <=", value, "unconfirmedCount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedCountIn(List<Double> values) {
            addCriterion("unconfirmed_count in", values, "unconfirmedCount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedCountNotIn(List<Double> values) {
            addCriterion("unconfirmed_count not in", values, "unconfirmedCount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedCountBetween(Double value1, Double value2) {
            addCriterion("unconfirmed_count between", value1, value2, "unconfirmedCount");
            return (Criteria) this;
        }

        public Criteria andUnconfirmedCountNotBetween(Double value1, Double value2) {
            addCriterion("unconfirmed_count not between", value1, value2, "unconfirmedCount");
            return (Criteria) this;
        }

        public Criteria andUsableRemainShareIsNull() {
            addCriterion("usable_remain_share is null");
            return (Criteria) this;
        }

        public Criteria andUsableRemainShareIsNotNull() {
            addCriterion("usable_remain_share is not null");
            return (Criteria) this;
        }

        public Criteria andUsableRemainShareEqualTo(Double value) {
            addCriterion("usable_remain_share =", value, "usableRemainShare");
            return (Criteria) this;
        }

        public Criteria andUsableRemainShareNotEqualTo(Double value) {
            addCriterion("usable_remain_share <>", value, "usableRemainShare");
            return (Criteria) this;
        }

        public Criteria andUsableRemainShareGreaterThan(Double value) {
            addCriterion("usable_remain_share >", value, "usableRemainShare");
            return (Criteria) this;
        }

        public Criteria andUsableRemainShareGreaterThanOrEqualTo(Double value) {
            addCriterion("usable_remain_share >=", value, "usableRemainShare");
            return (Criteria) this;
        }

        public Criteria andUsableRemainShareLessThan(Double value) {
            addCriterion("usable_remain_share <", value, "usableRemainShare");
            return (Criteria) this;
        }

        public Criteria andUsableRemainShareLessThanOrEqualTo(Double value) {
            addCriterion("usable_remain_share <=", value, "usableRemainShare");
            return (Criteria) this;
        }

        public Criteria andUsableRemainShareIn(List<Double> values) {
            addCriterion("usable_remain_share in", values, "usableRemainShare");
            return (Criteria) this;
        }

        public Criteria andUsableRemainShareNotIn(List<Double> values) {
            addCriterion("usable_remain_share not in", values, "usableRemainShare");
            return (Criteria) this;
        }

        public Criteria andUsableRemainShareBetween(Double value1, Double value2) {
            addCriterion("usable_remain_share between", value1, value2, "usableRemainShare");
            return (Criteria) this;
        }

        public Criteria andUsableRemainShareNotBetween(Double value1, Double value2) {
            addCriterion("usable_remain_share not between", value1, value2, "usableRemainShare");
            return (Criteria) this;
        }

        public Criteria andAutoInvestCountIsNull() {
            addCriterion("auto_invest_count is null");
            return (Criteria) this;
        }

        public Criteria andAutoInvestCountIsNotNull() {
            addCriterion("auto_invest_count is not null");
            return (Criteria) this;
        }

        public Criteria andAutoInvestCountEqualTo(Double value) {
            addCriterion("auto_invest_count =", value, "autoInvestCount");
            return (Criteria) this;
        }

        public Criteria andAutoInvestCountNotEqualTo(Double value) {
            addCriterion("auto_invest_count <>", value, "autoInvestCount");
            return (Criteria) this;
        }

        public Criteria andAutoInvestCountGreaterThan(Double value) {
            addCriterion("auto_invest_count >", value, "autoInvestCount");
            return (Criteria) this;
        }

        public Criteria andAutoInvestCountGreaterThanOrEqualTo(Double value) {
            addCriterion("auto_invest_count >=", value, "autoInvestCount");
            return (Criteria) this;
        }

        public Criteria andAutoInvestCountLessThan(Double value) {
            addCriterion("auto_invest_count <", value, "autoInvestCount");
            return (Criteria) this;
        }

        public Criteria andAutoInvestCountLessThanOrEqualTo(Double value) {
            addCriterion("auto_invest_count <=", value, "autoInvestCount");
            return (Criteria) this;
        }

        public Criteria andAutoInvestCountIn(List<Double> values) {
            addCriterion("auto_invest_count in", values, "autoInvestCount");
            return (Criteria) this;
        }

        public Criteria andAutoInvestCountNotIn(List<Double> values) {
            addCriterion("auto_invest_count not in", values, "autoInvestCount");
            return (Criteria) this;
        }

        public Criteria andAutoInvestCountBetween(Double value1, Double value2) {
            addCriterion("auto_invest_count between", value1, value2, "autoInvestCount");
            return (Criteria) this;
        }

        public Criteria andAutoInvestCountNotBetween(Double value1, Double value2) {
            addCriterion("auto_invest_count not between", value1, value2, "autoInvestCount");
            return (Criteria) this;
        }

        public Criteria andHoldGainRateIsNull() {
            addCriterion("hold_gain_rate is null");
            return (Criteria) this;
        }

        public Criteria andHoldGainRateIsNotNull() {
            addCriterion("hold_gain_rate is not null");
            return (Criteria) this;
        }

        public Criteria andHoldGainRateEqualTo(Double value) {
            addCriterion("hold_gain_rate =", value, "holdGainRate");
            return (Criteria) this;
        }

        public Criteria andHoldGainRateNotEqualTo(Double value) {
            addCriterion("hold_gain_rate <>", value, "holdGainRate");
            return (Criteria) this;
        }

        public Criteria andHoldGainRateGreaterThan(Double value) {
            addCriterion("hold_gain_rate >", value, "holdGainRate");
            return (Criteria) this;
        }

        public Criteria andHoldGainRateGreaterThanOrEqualTo(Double value) {
            addCriterion("hold_gain_rate >=", value, "holdGainRate");
            return (Criteria) this;
        }

        public Criteria andHoldGainRateLessThan(Double value) {
            addCriterion("hold_gain_rate <", value, "holdGainRate");
            return (Criteria) this;
        }

        public Criteria andHoldGainRateLessThanOrEqualTo(Double value) {
            addCriterion("hold_gain_rate <=", value, "holdGainRate");
            return (Criteria) this;
        }

        public Criteria andHoldGainRateIn(List<Double> values) {
            addCriterion("hold_gain_rate in", values, "holdGainRate");
            return (Criteria) this;
        }

        public Criteria andHoldGainRateNotIn(List<Double> values) {
            addCriterion("hold_gain_rate not in", values, "holdGainRate");
            return (Criteria) this;
        }

        public Criteria andHoldGainRateBetween(Double value1, Double value2) {
            addCriterion("hold_gain_rate between", value1, value2, "holdGainRate");
            return (Criteria) this;
        }

        public Criteria andHoldGainRateNotBetween(Double value1, Double value2) {
            addCriterion("hold_gain_rate not between", value1, value2, "holdGainRate");
            return (Criteria) this;
        }

        public Criteria andTotalGainRateIsNull() {
            addCriterion("total_gain_rate is null");
            return (Criteria) this;
        }

        public Criteria andTotalGainRateIsNotNull() {
            addCriterion("total_gain_rate is not null");
            return (Criteria) this;
        }

        public Criteria andTotalGainRateEqualTo(Double value) {
            addCriterion("total_gain_rate =", value, "totalGainRate");
            return (Criteria) this;
        }

        public Criteria andTotalGainRateNotEqualTo(Double value) {
            addCriterion("total_gain_rate <>", value, "totalGainRate");
            return (Criteria) this;
        }

        public Criteria andTotalGainRateGreaterThan(Double value) {
            addCriterion("total_gain_rate >", value, "totalGainRate");
            return (Criteria) this;
        }

        public Criteria andTotalGainRateGreaterThanOrEqualTo(Double value) {
            addCriterion("total_gain_rate >=", value, "totalGainRate");
            return (Criteria) this;
        }

        public Criteria andTotalGainRateLessThan(Double value) {
            addCriterion("total_gain_rate <", value, "totalGainRate");
            return (Criteria) this;
        }

        public Criteria andTotalGainRateLessThanOrEqualTo(Double value) {
            addCriterion("total_gain_rate <=", value, "totalGainRate");
            return (Criteria) this;
        }

        public Criteria andTotalGainRateIn(List<Double> values) {
            addCriterion("total_gain_rate in", values, "totalGainRate");
            return (Criteria) this;
        }

        public Criteria andTotalGainRateNotIn(List<Double> values) {
            addCriterion("total_gain_rate not in", values, "totalGainRate");
            return (Criteria) this;
        }

        public Criteria andTotalGainRateBetween(Double value1, Double value2) {
            addCriterion("total_gain_rate between", value1, value2, "totalGainRate");
            return (Criteria) this;
        }

        public Criteria andTotalGainRateNotBetween(Double value1, Double value2) {
            addCriterion("total_gain_rate not between", value1, value2, "totalGainRate");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andHoldingCostIsNull() {
            addCriterion("holding_cost is null");
            return (Criteria) this;
        }

        public Criteria andHoldingCostIsNotNull() {
            addCriterion("holding_cost is not null");
            return (Criteria) this;
        }

        public Criteria andHoldingCostEqualTo(Double value) {
            addCriterion("holding_cost =", value, "holdingCost");
            return (Criteria) this;
        }

        public Criteria andHoldingCostNotEqualTo(Double value) {
            addCriterion("holding_cost <>", value, "holdingCost");
            return (Criteria) this;
        }

        public Criteria andHoldingCostGreaterThan(Double value) {
            addCriterion("holding_cost >", value, "holdingCost");
            return (Criteria) this;
        }

        public Criteria andHoldingCostGreaterThanOrEqualTo(Double value) {
            addCriterion("holding_cost >=", value, "holdingCost");
            return (Criteria) this;
        }

        public Criteria andHoldingCostLessThan(Double value) {
            addCriterion("holding_cost <", value, "holdingCost");
            return (Criteria) this;
        }

        public Criteria andHoldingCostLessThanOrEqualTo(Double value) {
            addCriterion("holding_cost <=", value, "holdingCost");
            return (Criteria) this;
        }

        public Criteria andHoldingCostIn(List<Double> values) {
            addCriterion("holding_cost in", values, "holdingCost");
            return (Criteria) this;
        }

        public Criteria andHoldingCostNotIn(List<Double> values) {
            addCriterion("holding_cost not in", values, "holdingCost");
            return (Criteria) this;
        }

        public Criteria andHoldingCostBetween(Double value1, Double value2) {
            addCriterion("holding_cost between", value1, value2, "holdingCost");
            return (Criteria) this;
        }

        public Criteria andHoldingCostNotBetween(Double value1, Double value2) {
            addCriterion("holding_cost not between", value1, value2, "holdingCost");
            return (Criteria) this;
        }

        public Criteria andNavGuzhiIsNull() {
            addCriterion("nav_guzhi is null");
            return (Criteria) this;
        }

        public Criteria andNavGuzhiIsNotNull() {
            addCriterion("nav_guzhi is not null");
            return (Criteria) this;
        }

        public Criteria andNavGuzhiEqualTo(Double value) {
            addCriterion("nav_guzhi =", value, "navGuzhi");
            return (Criteria) this;
        }

        public Criteria andNavGuzhiNotEqualTo(Double value) {
            addCriterion("nav_guzhi <>", value, "navGuzhi");
            return (Criteria) this;
        }

        public Criteria andNavGuzhiGreaterThan(Double value) {
            addCriterion("nav_guzhi >", value, "navGuzhi");
            return (Criteria) this;
        }

        public Criteria andNavGuzhiGreaterThanOrEqualTo(Double value) {
            addCriterion("nav_guzhi >=", value, "navGuzhi");
            return (Criteria) this;
        }

        public Criteria andNavGuzhiLessThan(Double value) {
            addCriterion("nav_guzhi <", value, "navGuzhi");
            return (Criteria) this;
        }

        public Criteria andNavGuzhiLessThanOrEqualTo(Double value) {
            addCriterion("nav_guzhi <=", value, "navGuzhi");
            return (Criteria) this;
        }

        public Criteria andNavGuzhiIn(List<Double> values) {
            addCriterion("nav_guzhi in", values, "navGuzhi");
            return (Criteria) this;
        }

        public Criteria andNavGuzhiNotIn(List<Double> values) {
            addCriterion("nav_guzhi not in", values, "navGuzhi");
            return (Criteria) this;
        }

        public Criteria andNavGuzhiBetween(Double value1, Double value2) {
            addCriterion("nav_guzhi between", value1, value2, "navGuzhi");
            return (Criteria) this;
        }

        public Criteria andNavGuzhiNotBetween(Double value1, Double value2) {
            addCriterion("nav_guzhi not between", value1, value2, "navGuzhi");
            return (Criteria) this;
        }

        public Criteria andNavIsNull() {
            addCriterion("nav is null");
            return (Criteria) this;
        }

        public Criteria andNavIsNotNull() {
            addCriterion("nav is not null");
            return (Criteria) this;
        }

        public Criteria andNavEqualTo(Double value) {
            addCriterion("nav =", value, "nav");
            return (Criteria) this;
        }

        public Criteria andNavNotEqualTo(Double value) {
            addCriterion("nav <>", value, "nav");
            return (Criteria) this;
        }

        public Criteria andNavGreaterThan(Double value) {
            addCriterion("nav >", value, "nav");
            return (Criteria) this;
        }

        public Criteria andNavGreaterThanOrEqualTo(Double value) {
            addCriterion("nav >=", value, "nav");
            return (Criteria) this;
        }

        public Criteria andNavLessThan(Double value) {
            addCriterion("nav <", value, "nav");
            return (Criteria) this;
        }

        public Criteria andNavLessThanOrEqualTo(Double value) {
            addCriterion("nav <=", value, "nav");
            return (Criteria) this;
        }

        public Criteria andNavIn(List<Double> values) {
            addCriterion("nav in", values, "nav");
            return (Criteria) this;
        }

        public Criteria andNavNotIn(List<Double> values) {
            addCriterion("nav not in", values, "nav");
            return (Criteria) this;
        }

        public Criteria andNavBetween(Double value1, Double value2) {
            addCriterion("nav between", value1, value2, "nav");
            return (Criteria) this;
        }

        public Criteria andNavNotBetween(Double value1, Double value2) {
            addCriterion("nav not between", value1, value2, "nav");
            return (Criteria) this;
        }

        public Criteria andNavGrtdIsNull() {
            addCriterion("nav_grtd is null");
            return (Criteria) this;
        }

        public Criteria andNavGrtdIsNotNull() {
            addCriterion("nav_grtd is not null");
            return (Criteria) this;
        }

        public Criteria andNavGrtdEqualTo(Double value) {
            addCriterion("nav_grtd =", value, "navGrtd");
            return (Criteria) this;
        }

        public Criteria andNavGrtdNotEqualTo(Double value) {
            addCriterion("nav_grtd <>", value, "navGrtd");
            return (Criteria) this;
        }

        public Criteria andNavGrtdGreaterThan(Double value) {
            addCriterion("nav_grtd >", value, "navGrtd");
            return (Criteria) this;
        }

        public Criteria andNavGrtdGreaterThanOrEqualTo(Double value) {
            addCriterion("nav_grtd >=", value, "navGrtd");
            return (Criteria) this;
        }

        public Criteria andNavGrtdLessThan(Double value) {
            addCriterion("nav_grtd <", value, "navGrtd");
            return (Criteria) this;
        }

        public Criteria andNavGrtdLessThanOrEqualTo(Double value) {
            addCriterion("nav_grtd <=", value, "navGrtd");
            return (Criteria) this;
        }

        public Criteria andNavGrtdIn(List<Double> values) {
            addCriterion("nav_grtd in", values, "navGrtd");
            return (Criteria) this;
        }

        public Criteria andNavGrtdNotIn(List<Double> values) {
            addCriterion("nav_grtd not in", values, "navGrtd");
            return (Criteria) this;
        }

        public Criteria andNavGrtdBetween(Double value1, Double value2) {
            addCriterion("nav_grtd between", value1, value2, "navGrtd");
            return (Criteria) this;
        }

        public Criteria andNavGrtdNotBetween(Double value1, Double value2) {
            addCriterion("nav_grtd not between", value1, value2, "navGrtd");
            return (Criteria) this;
        }

        public Criteria andTsIsNull() {
            addCriterion("ts is null");
            return (Criteria) this;
        }

        public Criteria andTsIsNotNull() {
            addCriterion("ts is not null");
            return (Criteria) this;
        }

        public Criteria andTsEqualTo(Date value) {
            addCriterion("ts =", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotEqualTo(Date value) {
            addCriterion("ts <>", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThan(Date value) {
            addCriterion("ts >", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThanOrEqualTo(Date value) {
            addCriterion("ts >=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThan(Date value) {
            addCriterion("ts <", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThanOrEqualTo(Date value) {
            addCriterion("ts <=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsIn(List<Date> values) {
            addCriterion("ts in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotIn(List<Date> values) {
            addCriterion("ts not in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsBetween(Date value1, Date value2) {
            addCriterion("ts between", value1, value2, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotBetween(Date value1, Date value2) {
            addCriterion("ts not between", value1, value2, "ts");
            return (Criteria) this;
        }

        public Criteria andProfitDocumentsIsNull() {
            addCriterion("profit_documents is null");
            return (Criteria) this;
        }

        public Criteria andProfitDocumentsIsNotNull() {
            addCriterion("profit_documents is not null");
            return (Criteria) this;
        }

        public Criteria andProfitDocumentsEqualTo(String value) {
            addCriterion("profit_documents =", value, "profitDocuments");
            return (Criteria) this;
        }

        public Criteria andProfitDocumentsNotEqualTo(String value) {
            addCriterion("profit_documents <>", value, "profitDocuments");
            return (Criteria) this;
        }

        public Criteria andProfitDocumentsGreaterThan(String value) {
            addCriterion("profit_documents >", value, "profitDocuments");
            return (Criteria) this;
        }

        public Criteria andProfitDocumentsGreaterThanOrEqualTo(String value) {
            addCriterion("profit_documents >=", value, "profitDocuments");
            return (Criteria) this;
        }

        public Criteria andProfitDocumentsLessThan(String value) {
            addCriterion("profit_documents <", value, "profitDocuments");
            return (Criteria) this;
        }

        public Criteria andProfitDocumentsLessThanOrEqualTo(String value) {
            addCriterion("profit_documents <=", value, "profitDocuments");
            return (Criteria) this;
        }

        public Criteria andProfitDocumentsLike(String value) {
            addCriterion("profit_documents like", value, "profitDocuments");
            return (Criteria) this;
        }

        public Criteria andProfitDocumentsNotLike(String value) {
            addCriterion("profit_documents not like", value, "profitDocuments");
            return (Criteria) this;
        }

        public Criteria andProfitDocumentsIn(List<String> values) {
            addCriterion("profit_documents in", values, "profitDocuments");
            return (Criteria) this;
        }

        public Criteria andProfitDocumentsNotIn(List<String> values) {
            addCriterion("profit_documents not in", values, "profitDocuments");
            return (Criteria) this;
        }

        public Criteria andProfitDocumentsBetween(String value1, String value2) {
            addCriterion("profit_documents between", value1, value2, "profitDocuments");
            return (Criteria) this;
        }

        public Criteria andProfitDocumentsNotBetween(String value1, String value2) {
            addCriterion("profit_documents not between", value1, value2, "profitDocuments");
            return (Criteria) this;
        }

        public Criteria andDateCreateIsNull() {
            addCriterion("date_create is null");
            return (Criteria) this;
        }

        public Criteria andDateCreateIsNotNull() {
            addCriterion("date_create is not null");
            return (Criteria) this;
        }

        public Criteria andDateCreateEqualTo(Date value) {
            addCriterion("date_create =", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateNotEqualTo(Date value) {
            addCriterion("date_create <>", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateGreaterThan(Date value) {
            addCriterion("date_create >", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("date_create >=", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateLessThan(Date value) {
            addCriterion("date_create <", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateLessThanOrEqualTo(Date value) {
            addCriterion("date_create <=", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateIn(List<Date> values) {
            addCriterion("date_create in", values, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateNotIn(List<Date> values) {
            addCriterion("date_create not in", values, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateBetween(Date value1, Date value2) {
            addCriterion("date_create between", value1, value2, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateNotBetween(Date value1, Date value2) {
            addCriterion("date_create not between", value1, value2, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateIsNull() {
            addCriterion("date_update is null");
            return (Criteria) this;
        }

        public Criteria andDateUpdateIsNotNull() {
            addCriterion("date_update is not null");
            return (Criteria) this;
        }

        public Criteria andDateUpdateEqualTo(Date value) {
            addCriterion("date_update =", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateNotEqualTo(Date value) {
            addCriterion("date_update <>", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateGreaterThan(Date value) {
            addCriterion("date_update >", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("date_update >=", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateLessThan(Date value) {
            addCriterion("date_update <", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateLessThanOrEqualTo(Date value) {
            addCriterion("date_update <=", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateIn(List<Date> values) {
            addCriterion("date_update in", values, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateNotIn(List<Date> values) {
            addCriterion("date_update not in", values, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateBetween(Date value1, Date value2) {
            addCriterion("date_update between", value1, value2, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateNotBetween(Date value1, Date value2) {
            addCriterion("date_update not between", value1, value2, "dateUpdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hold_fund
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 08 17:14:58 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hold_fund
     *
     * @mbggenerated Sun Sep 08 17:14:58 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public class BoundBuilder {
        protected Integer limit;

        protected Integer offset;

        public Integer limit() {
            return this.limit;
        }

        public BoundBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }

        public Integer offset() {
            return this.offset;
        }

        public BoundBuilder offset(Integer offset) {
            this.offset = offset;
            return this;
        }

        public THoldFundCriteria build() {
            THoldFundCriteria.this.limit = limit;
            THoldFundCriteria.this.offset = offset;
            return THoldFundCriteria.this;
        }
    }
}