package com.zsh.labouCapital.dao.dto;

import java.io.Serializable;
import java.util.Date;

public class THoldFund implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.id
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.fund_code
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private String fundCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.fund_name
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private String fundName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.hold_cost
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double holdCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.accum_cost
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double accumCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.market_value
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double marketValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.volume
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.total_gain
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double totalGain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.hold_gain
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double holdGain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.daily_gain
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double dailyGain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.unconfirmed_amount
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double unconfirmedAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.unconfirmed_volume
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double unconfirmedVolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.unconfirmed_count
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double unconfirmedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.usable_remain_share
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double usableRemainShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.auto_invest_count
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double autoInvestCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.hold_gain_rate
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double holdGainRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.total_gain_rate
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double totalGainRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.type
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.holding_cost
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double holdingCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.nav_guzhi
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double navGuzhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.nav
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double nav;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.nav_grtd
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Double navGrtd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.ts
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Date ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.profit_documents
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private String profitDocuments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.date_create
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Date dateCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hold_fund.date_update
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private Date dateUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hold_fund
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.id
     *
     * @return the value of t_hold_fund.id
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.id
     *
     * @param id the value for t_hold_fund.id
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.fund_code
     *
     * @return the value of t_hold_fund.fund_code
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.fund_code
     *
     * @param fundCode the value for t_hold_fund.fund_code
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode == null ? null : fundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.fund_name
     *
     * @return the value of t_hold_fund.fund_name
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.fund_name
     *
     * @param fundName the value for t_hold_fund.fund_name
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setFundName(String fundName) {
        this.fundName = fundName == null ? null : fundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.hold_cost
     *
     * @return the value of t_hold_fund.hold_cost
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getHoldCost() {
        return holdCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.hold_cost
     *
     * @param holdCost the value for t_hold_fund.hold_cost
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setHoldCost(Double holdCost) {
        this.holdCost = holdCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.accum_cost
     *
     * @return the value of t_hold_fund.accum_cost
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getAccumCost() {
        return accumCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.accum_cost
     *
     * @param accumCost the value for t_hold_fund.accum_cost
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setAccumCost(Double accumCost) {
        this.accumCost = accumCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.market_value
     *
     * @return the value of t_hold_fund.market_value
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getMarketValue() {
        return marketValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.market_value
     *
     * @param marketValue the value for t_hold_fund.market_value
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setMarketValue(Double marketValue) {
        this.marketValue = marketValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.volume
     *
     * @return the value of t_hold_fund.volume
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.volume
     *
     * @param volume the value for t_hold_fund.volume
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setVolume(Double volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.total_gain
     *
     * @return the value of t_hold_fund.total_gain
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getTotalGain() {
        return totalGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.total_gain
     *
     * @param totalGain the value for t_hold_fund.total_gain
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setTotalGain(Double totalGain) {
        this.totalGain = totalGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.hold_gain
     *
     * @return the value of t_hold_fund.hold_gain
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getHoldGain() {
        return holdGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.hold_gain
     *
     * @param holdGain the value for t_hold_fund.hold_gain
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setHoldGain(Double holdGain) {
        this.holdGain = holdGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.daily_gain
     *
     * @return the value of t_hold_fund.daily_gain
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getDailyGain() {
        return dailyGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.daily_gain
     *
     * @param dailyGain the value for t_hold_fund.daily_gain
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setDailyGain(Double dailyGain) {
        this.dailyGain = dailyGain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.unconfirmed_amount
     *
     * @return the value of t_hold_fund.unconfirmed_amount
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getUnconfirmedAmount() {
        return unconfirmedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.unconfirmed_amount
     *
     * @param unconfirmedAmount the value for t_hold_fund.unconfirmed_amount
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setUnconfirmedAmount(Double unconfirmedAmount) {
        this.unconfirmedAmount = unconfirmedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.unconfirmed_volume
     *
     * @return the value of t_hold_fund.unconfirmed_volume
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getUnconfirmedVolume() {
        return unconfirmedVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.unconfirmed_volume
     *
     * @param unconfirmedVolume the value for t_hold_fund.unconfirmed_volume
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setUnconfirmedVolume(Double unconfirmedVolume) {
        this.unconfirmedVolume = unconfirmedVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.unconfirmed_count
     *
     * @return the value of t_hold_fund.unconfirmed_count
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getUnconfirmedCount() {
        return unconfirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.unconfirmed_count
     *
     * @param unconfirmedCount the value for t_hold_fund.unconfirmed_count
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setUnconfirmedCount(Double unconfirmedCount) {
        this.unconfirmedCount = unconfirmedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.usable_remain_share
     *
     * @return the value of t_hold_fund.usable_remain_share
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getUsableRemainShare() {
        return usableRemainShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.usable_remain_share
     *
     * @param usableRemainShare the value for t_hold_fund.usable_remain_share
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setUsableRemainShare(Double usableRemainShare) {
        this.usableRemainShare = usableRemainShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.auto_invest_count
     *
     * @return the value of t_hold_fund.auto_invest_count
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getAutoInvestCount() {
        return autoInvestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.auto_invest_count
     *
     * @param autoInvestCount the value for t_hold_fund.auto_invest_count
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setAutoInvestCount(Double autoInvestCount) {
        this.autoInvestCount = autoInvestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.hold_gain_rate
     *
     * @return the value of t_hold_fund.hold_gain_rate
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getHoldGainRate() {
        return holdGainRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.hold_gain_rate
     *
     * @param holdGainRate the value for t_hold_fund.hold_gain_rate
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setHoldGainRate(Double holdGainRate) {
        this.holdGainRate = holdGainRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.total_gain_rate
     *
     * @return the value of t_hold_fund.total_gain_rate
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getTotalGainRate() {
        return totalGainRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.total_gain_rate
     *
     * @param totalGainRate the value for t_hold_fund.total_gain_rate
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setTotalGainRate(Double totalGainRate) {
        this.totalGainRate = totalGainRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.type
     *
     * @return the value of t_hold_fund.type
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.type
     *
     * @param type the value for t_hold_fund.type
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.holding_cost
     *
     * @return the value of t_hold_fund.holding_cost
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getHoldingCost() {
        return holdingCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.holding_cost
     *
     * @param holdingCost the value for t_hold_fund.holding_cost
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setHoldingCost(Double holdingCost) {
        this.holdingCost = holdingCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.nav_guzhi
     *
     * @return the value of t_hold_fund.nav_guzhi
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getNavGuzhi() {
        return navGuzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.nav_guzhi
     *
     * @param navGuzhi the value for t_hold_fund.nav_guzhi
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setNavGuzhi(Double navGuzhi) {
        this.navGuzhi = navGuzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.nav
     *
     * @return the value of t_hold_fund.nav
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getNav() {
        return nav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.nav
     *
     * @param nav the value for t_hold_fund.nav
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setNav(Double nav) {
        this.nav = nav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.nav_grtd
     *
     * @return the value of t_hold_fund.nav_grtd
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Double getNavGrtd() {
        return navGrtd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.nav_grtd
     *
     * @param navGrtd the value for t_hold_fund.nav_grtd
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setNavGrtd(Double navGrtd) {
        this.navGrtd = navGrtd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.ts
     *
     * @return the value of t_hold_fund.ts
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.ts
     *
     * @param ts the value for t_hold_fund.ts
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.profit_documents
     *
     * @return the value of t_hold_fund.profit_documents
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public String getProfitDocuments() {
        return profitDocuments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.profit_documents
     *
     * @param profitDocuments the value for t_hold_fund.profit_documents
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setProfitDocuments(String profitDocuments) {
        this.profitDocuments = profitDocuments == null ? null : profitDocuments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.date_create
     *
     * @return the value of t_hold_fund.date_create
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Date getDateCreate() {
        return dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.date_create
     *
     * @param dateCreate the value for t_hold_fund.date_create
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hold_fund.date_update
     *
     * @return the value of t_hold_fund.date_update
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Date getDateUpdate() {
        return dateUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hold_fund.date_update
     *
     * @param dateUpdate the value for t_hold_fund.date_update
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setDateUpdate(Date dateUpdate) {
        this.dateUpdate = dateUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hold_fund
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fundCode=").append(fundCode);
        sb.append(", fundName=").append(fundName);
        sb.append(", holdCost=").append(holdCost);
        sb.append(", accumCost=").append(accumCost);
        sb.append(", marketValue=").append(marketValue);
        sb.append(", volume=").append(volume);
        sb.append(", totalGain=").append(totalGain);
        sb.append(", holdGain=").append(holdGain);
        sb.append(", dailyGain=").append(dailyGain);
        sb.append(", unconfirmedAmount=").append(unconfirmedAmount);
        sb.append(", unconfirmedVolume=").append(unconfirmedVolume);
        sb.append(", unconfirmedCount=").append(unconfirmedCount);
        sb.append(", usableRemainShare=").append(usableRemainShare);
        sb.append(", autoInvestCount=").append(autoInvestCount);
        sb.append(", holdGainRate=").append(holdGainRate);
        sb.append(", totalGainRate=").append(totalGainRate);
        sb.append(", type=").append(type);
        sb.append(", holdingCost=").append(holdingCost);
        sb.append(", navGuzhi=").append(navGuzhi);
        sb.append(", nav=").append(nav);
        sb.append(", navGrtd=").append(navGrtd);
        sb.append(", ts=").append(ts);
        sb.append(", profitDocuments=").append(profitDocuments);
        sb.append(", dateCreate=").append(dateCreate);
        sb.append(", dateUpdate=").append(dateUpdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}