package com.zsh.labouCapital.dao.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TNetWorthLastCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    protected List<Criteria> oredCriteria;

    protected Integer limit;

    protected Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public TNetWorthLastCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return this.limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return this.offset;
    }

    public BoundBuilder boundBuilder() {
        return new BoundBuilder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFundCodeIsNull() {
            addCriterion("fund_code is null");
            return (Criteria) this;
        }

        public Criteria andFundCodeIsNotNull() {
            addCriterion("fund_code is not null");
            return (Criteria) this;
        }

        public Criteria andFundCodeEqualTo(String value) {
            addCriterion("fund_code =", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotEqualTo(String value) {
            addCriterion("fund_code <>", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeGreaterThan(String value) {
            addCriterion("fund_code >", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeGreaterThanOrEqualTo(String value) {
            addCriterion("fund_code >=", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLessThan(String value) {
            addCriterion("fund_code <", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLessThanOrEqualTo(String value) {
            addCriterion("fund_code <=", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeLike(String value) {
            addCriterion("fund_code like", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotLike(String value) {
            addCriterion("fund_code not like", value, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeIn(List<String> values) {
            addCriterion("fund_code in", values, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotIn(List<String> values) {
            addCriterion("fund_code not in", values, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeBetween(String value1, String value2) {
            addCriterion("fund_code between", value1, value2, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundCodeNotBetween(String value1, String value2) {
            addCriterion("fund_code not between", value1, value2, "fundCode");
            return (Criteria) this;
        }

        public Criteria andFundNameIsNull() {
            addCriterion("fund_name is null");
            return (Criteria) this;
        }

        public Criteria andFundNameIsNotNull() {
            addCriterion("fund_name is not null");
            return (Criteria) this;
        }

        public Criteria andFundNameEqualTo(String value) {
            addCriterion("fund_name =", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameNotEqualTo(String value) {
            addCriterion("fund_name <>", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameGreaterThan(String value) {
            addCriterion("fund_name >", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameGreaterThanOrEqualTo(String value) {
            addCriterion("fund_name >=", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameLessThan(String value) {
            addCriterion("fund_name <", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameLessThanOrEqualTo(String value) {
            addCriterion("fund_name <=", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameLike(String value) {
            addCriterion("fund_name like", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameNotLike(String value) {
            addCriterion("fund_name not like", value, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameIn(List<String> values) {
            addCriterion("fund_name in", values, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameNotIn(List<String> values) {
            addCriterion("fund_name not in", values, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameBetween(String value1, String value2) {
            addCriterion("fund_name between", value1, value2, "fundName");
            return (Criteria) this;
        }

        public Criteria andFundNameNotBetween(String value1, String value2) {
            addCriterion("fund_name not between", value1, value2, "fundName");
            return (Criteria) this;
        }

        public Criteria andNowNetWorthIsNull() {
            addCriterion("now_net_worth is null");
            return (Criteria) this;
        }

        public Criteria andNowNetWorthIsNotNull() {
            addCriterion("now_net_worth is not null");
            return (Criteria) this;
        }

        public Criteria andNowNetWorthEqualTo(Double value) {
            addCriterion("now_net_worth =", value, "nowNetWorth");
            return (Criteria) this;
        }

        public Criteria andNowNetWorthNotEqualTo(Double value) {
            addCriterion("now_net_worth <>", value, "nowNetWorth");
            return (Criteria) this;
        }

        public Criteria andNowNetWorthGreaterThan(Double value) {
            addCriterion("now_net_worth >", value, "nowNetWorth");
            return (Criteria) this;
        }

        public Criteria andNowNetWorthGreaterThanOrEqualTo(Double value) {
            addCriterion("now_net_worth >=", value, "nowNetWorth");
            return (Criteria) this;
        }

        public Criteria andNowNetWorthLessThan(Double value) {
            addCriterion("now_net_worth <", value, "nowNetWorth");
            return (Criteria) this;
        }

        public Criteria andNowNetWorthLessThanOrEqualTo(Double value) {
            addCriterion("now_net_worth <=", value, "nowNetWorth");
            return (Criteria) this;
        }

        public Criteria andNowNetWorthIn(List<Double> values) {
            addCriterion("now_net_worth in", values, "nowNetWorth");
            return (Criteria) this;
        }

        public Criteria andNowNetWorthNotIn(List<Double> values) {
            addCriterion("now_net_worth not in", values, "nowNetWorth");
            return (Criteria) this;
        }

        public Criteria andNowNetWorthBetween(Double value1, Double value2) {
            addCriterion("now_net_worth between", value1, value2, "nowNetWorth");
            return (Criteria) this;
        }

        public Criteria andNowNetWorthNotBetween(Double value1, Double value2) {
            addCriterion("now_net_worth not between", value1, value2, "nowNetWorth");
            return (Criteria) this;
        }

        public Criteria andYesterdayNetWorthIsNull() {
            addCriterion("yesterday_net_worth is null");
            return (Criteria) this;
        }

        public Criteria andYesterdayNetWorthIsNotNull() {
            addCriterion("yesterday_net_worth is not null");
            return (Criteria) this;
        }

        public Criteria andYesterdayNetWorthEqualTo(Double value) {
            addCriterion("yesterday_net_worth =", value, "yesterdayNetWorth");
            return (Criteria) this;
        }

        public Criteria andYesterdayNetWorthNotEqualTo(Double value) {
            addCriterion("yesterday_net_worth <>", value, "yesterdayNetWorth");
            return (Criteria) this;
        }

        public Criteria andYesterdayNetWorthGreaterThan(Double value) {
            addCriterion("yesterday_net_worth >", value, "yesterdayNetWorth");
            return (Criteria) this;
        }

        public Criteria andYesterdayNetWorthGreaterThanOrEqualTo(Double value) {
            addCriterion("yesterday_net_worth >=", value, "yesterdayNetWorth");
            return (Criteria) this;
        }

        public Criteria andYesterdayNetWorthLessThan(Double value) {
            addCriterion("yesterday_net_worth <", value, "yesterdayNetWorth");
            return (Criteria) this;
        }

        public Criteria andYesterdayNetWorthLessThanOrEqualTo(Double value) {
            addCriterion("yesterday_net_worth <=", value, "yesterdayNetWorth");
            return (Criteria) this;
        }

        public Criteria andYesterdayNetWorthIn(List<Double> values) {
            addCriterion("yesterday_net_worth in", values, "yesterdayNetWorth");
            return (Criteria) this;
        }

        public Criteria andYesterdayNetWorthNotIn(List<Double> values) {
            addCriterion("yesterday_net_worth not in", values, "yesterdayNetWorth");
            return (Criteria) this;
        }

        public Criteria andYesterdayNetWorthBetween(Double value1, Double value2) {
            addCriterion("yesterday_net_worth between", value1, value2, "yesterdayNetWorth");
            return (Criteria) this;
        }

        public Criteria andYesterdayNetWorthNotBetween(Double value1, Double value2) {
            addCriterion("yesterday_net_worth not between", value1, value2, "yesterdayNetWorth");
            return (Criteria) this;
        }

        public Criteria andGuzhiAddRateIsNull() {
            addCriterion("guzhi_add_rate is null");
            return (Criteria) this;
        }

        public Criteria andGuzhiAddRateIsNotNull() {
            addCriterion("guzhi_add_rate is not null");
            return (Criteria) this;
        }

        public Criteria andGuzhiAddRateEqualTo(Double value) {
            addCriterion("guzhi_add_rate =", value, "guzhiAddRate");
            return (Criteria) this;
        }

        public Criteria andGuzhiAddRateNotEqualTo(Double value) {
            addCriterion("guzhi_add_rate <>", value, "guzhiAddRate");
            return (Criteria) this;
        }

        public Criteria andGuzhiAddRateGreaterThan(Double value) {
            addCriterion("guzhi_add_rate >", value, "guzhiAddRate");
            return (Criteria) this;
        }

        public Criteria andGuzhiAddRateGreaterThanOrEqualTo(Double value) {
            addCriterion("guzhi_add_rate >=", value, "guzhiAddRate");
            return (Criteria) this;
        }

        public Criteria andGuzhiAddRateLessThan(Double value) {
            addCriterion("guzhi_add_rate <", value, "guzhiAddRate");
            return (Criteria) this;
        }

        public Criteria andGuzhiAddRateLessThanOrEqualTo(Double value) {
            addCriterion("guzhi_add_rate <=", value, "guzhiAddRate");
            return (Criteria) this;
        }

        public Criteria andGuzhiAddRateIn(List<Double> values) {
            addCriterion("guzhi_add_rate in", values, "guzhiAddRate");
            return (Criteria) this;
        }

        public Criteria andGuzhiAddRateNotIn(List<Double> values) {
            addCriterion("guzhi_add_rate not in", values, "guzhiAddRate");
            return (Criteria) this;
        }

        public Criteria andGuzhiAddRateBetween(Double value1, Double value2) {
            addCriterion("guzhi_add_rate between", value1, value2, "guzhiAddRate");
            return (Criteria) this;
        }

        public Criteria andGuzhiAddRateNotBetween(Double value1, Double value2) {
            addCriterion("guzhi_add_rate not between", value1, value2, "guzhiAddRate");
            return (Criteria) this;
        }

        public Criteria andAvgLine30IsNull() {
            addCriterion("avg_line30 is null");
            return (Criteria) this;
        }

        public Criteria andAvgLine30IsNotNull() {
            addCriterion("avg_line30 is not null");
            return (Criteria) this;
        }

        public Criteria andAvgLine30EqualTo(Double value) {
            addCriterion("avg_line30 =", value, "avgLine30");
            return (Criteria) this;
        }

        public Criteria andAvgLine30NotEqualTo(Double value) {
            addCriterion("avg_line30 <>", value, "avgLine30");
            return (Criteria) this;
        }

        public Criteria andAvgLine30GreaterThan(Double value) {
            addCriterion("avg_line30 >", value, "avgLine30");
            return (Criteria) this;
        }

        public Criteria andAvgLine30GreaterThanOrEqualTo(Double value) {
            addCriterion("avg_line30 >=", value, "avgLine30");
            return (Criteria) this;
        }

        public Criteria andAvgLine30LessThan(Double value) {
            addCriterion("avg_line30 <", value, "avgLine30");
            return (Criteria) this;
        }

        public Criteria andAvgLine30LessThanOrEqualTo(Double value) {
            addCriterion("avg_line30 <=", value, "avgLine30");
            return (Criteria) this;
        }

        public Criteria andAvgLine30In(List<Double> values) {
            addCriterion("avg_line30 in", values, "avgLine30");
            return (Criteria) this;
        }

        public Criteria andAvgLine30NotIn(List<Double> values) {
            addCriterion("avg_line30 not in", values, "avgLine30");
            return (Criteria) this;
        }

        public Criteria andAvgLine30Between(Double value1, Double value2) {
            addCriterion("avg_line30 between", value1, value2, "avgLine30");
            return (Criteria) this;
        }

        public Criteria andAvgLine30NotBetween(Double value1, Double value2) {
            addCriterion("avg_line30 not between", value1, value2, "avgLine30");
            return (Criteria) this;
        }

        public Criteria andAvgLine60IsNull() {
            addCriterion("avg_line60 is null");
            return (Criteria) this;
        }

        public Criteria andAvgLine60IsNotNull() {
            addCriterion("avg_line60 is not null");
            return (Criteria) this;
        }

        public Criteria andAvgLine60EqualTo(Double value) {
            addCriterion("avg_line60 =", value, "avgLine60");
            return (Criteria) this;
        }

        public Criteria andAvgLine60NotEqualTo(Double value) {
            addCriterion("avg_line60 <>", value, "avgLine60");
            return (Criteria) this;
        }

        public Criteria andAvgLine60GreaterThan(Double value) {
            addCriterion("avg_line60 >", value, "avgLine60");
            return (Criteria) this;
        }

        public Criteria andAvgLine60GreaterThanOrEqualTo(Double value) {
            addCriterion("avg_line60 >=", value, "avgLine60");
            return (Criteria) this;
        }

        public Criteria andAvgLine60LessThan(Double value) {
            addCriterion("avg_line60 <", value, "avgLine60");
            return (Criteria) this;
        }

        public Criteria andAvgLine60LessThanOrEqualTo(Double value) {
            addCriterion("avg_line60 <=", value, "avgLine60");
            return (Criteria) this;
        }

        public Criteria andAvgLine60In(List<Double> values) {
            addCriterion("avg_line60 in", values, "avgLine60");
            return (Criteria) this;
        }

        public Criteria andAvgLine60NotIn(List<Double> values) {
            addCriterion("avg_line60 not in", values, "avgLine60");
            return (Criteria) this;
        }

        public Criteria andAvgLine60Between(Double value1, Double value2) {
            addCriterion("avg_line60 between", value1, value2, "avgLine60");
            return (Criteria) this;
        }

        public Criteria andAvgLine60NotBetween(Double value1, Double value2) {
            addCriterion("avg_line60 not between", value1, value2, "avgLine60");
            return (Criteria) this;
        }

        public Criteria andAvgLine90IsNull() {
            addCriterion("avg_line90 is null");
            return (Criteria) this;
        }

        public Criteria andAvgLine90IsNotNull() {
            addCriterion("avg_line90 is not null");
            return (Criteria) this;
        }

        public Criteria andAvgLine90EqualTo(Double value) {
            addCriterion("avg_line90 =", value, "avgLine90");
            return (Criteria) this;
        }

        public Criteria andAvgLine90NotEqualTo(Double value) {
            addCriterion("avg_line90 <>", value, "avgLine90");
            return (Criteria) this;
        }

        public Criteria andAvgLine90GreaterThan(Double value) {
            addCriterion("avg_line90 >", value, "avgLine90");
            return (Criteria) this;
        }

        public Criteria andAvgLine90GreaterThanOrEqualTo(Double value) {
            addCriterion("avg_line90 >=", value, "avgLine90");
            return (Criteria) this;
        }

        public Criteria andAvgLine90LessThan(Double value) {
            addCriterion("avg_line90 <", value, "avgLine90");
            return (Criteria) this;
        }

        public Criteria andAvgLine90LessThanOrEqualTo(Double value) {
            addCriterion("avg_line90 <=", value, "avgLine90");
            return (Criteria) this;
        }

        public Criteria andAvgLine90In(List<Double> values) {
            addCriterion("avg_line90 in", values, "avgLine90");
            return (Criteria) this;
        }

        public Criteria andAvgLine90NotIn(List<Double> values) {
            addCriterion("avg_line90 not in", values, "avgLine90");
            return (Criteria) this;
        }

        public Criteria andAvgLine90Between(Double value1, Double value2) {
            addCriterion("avg_line90 between", value1, value2, "avgLine90");
            return (Criteria) this;
        }

        public Criteria andAvgLine90NotBetween(Double value1, Double value2) {
            addCriterion("avg_line90 not between", value1, value2, "avgLine90");
            return (Criteria) this;
        }

        public Criteria andAvgLine120IsNull() {
            addCriterion("avg_line120 is null");
            return (Criteria) this;
        }

        public Criteria andAvgLine120IsNotNull() {
            addCriterion("avg_line120 is not null");
            return (Criteria) this;
        }

        public Criteria andAvgLine120EqualTo(Double value) {
            addCriterion("avg_line120 =", value, "avgLine120");
            return (Criteria) this;
        }

        public Criteria andAvgLine120NotEqualTo(Double value) {
            addCriterion("avg_line120 <>", value, "avgLine120");
            return (Criteria) this;
        }

        public Criteria andAvgLine120GreaterThan(Double value) {
            addCriterion("avg_line120 >", value, "avgLine120");
            return (Criteria) this;
        }

        public Criteria andAvgLine120GreaterThanOrEqualTo(Double value) {
            addCriterion("avg_line120 >=", value, "avgLine120");
            return (Criteria) this;
        }

        public Criteria andAvgLine120LessThan(Double value) {
            addCriterion("avg_line120 <", value, "avgLine120");
            return (Criteria) this;
        }

        public Criteria andAvgLine120LessThanOrEqualTo(Double value) {
            addCriterion("avg_line120 <=", value, "avgLine120");
            return (Criteria) this;
        }

        public Criteria andAvgLine120In(List<Double> values) {
            addCriterion("avg_line120 in", values, "avgLine120");
            return (Criteria) this;
        }

        public Criteria andAvgLine120NotIn(List<Double> values) {
            addCriterion("avg_line120 not in", values, "avgLine120");
            return (Criteria) this;
        }

        public Criteria andAvgLine120Between(Double value1, Double value2) {
            addCriterion("avg_line120 between", value1, value2, "avgLine120");
            return (Criteria) this;
        }

        public Criteria andAvgLine120NotBetween(Double value1, Double value2) {
            addCriterion("avg_line120 not between", value1, value2, "avgLine120");
            return (Criteria) this;
        }

        public Criteria andAvgLine240IsNull() {
            addCriterion("avg_line240 is null");
            return (Criteria) this;
        }

        public Criteria andAvgLine240IsNotNull() {
            addCriterion("avg_line240 is not null");
            return (Criteria) this;
        }

        public Criteria andAvgLine240EqualTo(Double value) {
            addCriterion("avg_line240 =", value, "avgLine240");
            return (Criteria) this;
        }

        public Criteria andAvgLine240NotEqualTo(Double value) {
            addCriterion("avg_line240 <>", value, "avgLine240");
            return (Criteria) this;
        }

        public Criteria andAvgLine240GreaterThan(Double value) {
            addCriterion("avg_line240 >", value, "avgLine240");
            return (Criteria) this;
        }

        public Criteria andAvgLine240GreaterThanOrEqualTo(Double value) {
            addCriterion("avg_line240 >=", value, "avgLine240");
            return (Criteria) this;
        }

        public Criteria andAvgLine240LessThan(Double value) {
            addCriterion("avg_line240 <", value, "avgLine240");
            return (Criteria) this;
        }

        public Criteria andAvgLine240LessThanOrEqualTo(Double value) {
            addCriterion("avg_line240 <=", value, "avgLine240");
            return (Criteria) this;
        }

        public Criteria andAvgLine240In(List<Double> values) {
            addCriterion("avg_line240 in", values, "avgLine240");
            return (Criteria) this;
        }

        public Criteria andAvgLine240NotIn(List<Double> values) {
            addCriterion("avg_line240 not in", values, "avgLine240");
            return (Criteria) this;
        }

        public Criteria andAvgLine240Between(Double value1, Double value2) {
            addCriterion("avg_line240 between", value1, value2, "avgLine240");
            return (Criteria) this;
        }

        public Criteria andAvgLine240NotBetween(Double value1, Double value2) {
            addCriterion("avg_line240 not between", value1, value2, "avgLine240");
            return (Criteria) this;
        }

        public Criteria andIndexCodeIsNull() {
            addCriterion("index_code is null");
            return (Criteria) this;
        }

        public Criteria andIndexCodeIsNotNull() {
            addCriterion("index_code is not null");
            return (Criteria) this;
        }

        public Criteria andIndexCodeEqualTo(String value) {
            addCriterion("index_code =", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeNotEqualTo(String value) {
            addCriterion("index_code <>", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeGreaterThan(String value) {
            addCriterion("index_code >", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeGreaterThanOrEqualTo(String value) {
            addCriterion("index_code >=", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeLessThan(String value) {
            addCriterion("index_code <", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeLessThanOrEqualTo(String value) {
            addCriterion("index_code <=", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeLike(String value) {
            addCriterion("index_code like", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeNotLike(String value) {
            addCriterion("index_code not like", value, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeIn(List<String> values) {
            addCriterion("index_code in", values, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeNotIn(List<String> values) {
            addCriterion("index_code not in", values, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeBetween(String value1, String value2) {
            addCriterion("index_code between", value1, value2, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexCodeNotBetween(String value1, String value2) {
            addCriterion("index_code not between", value1, value2, "indexCode");
            return (Criteria) this;
        }

        public Criteria andIndexPeIsNull() {
            addCriterion("index_pe is null");
            return (Criteria) this;
        }

        public Criteria andIndexPeIsNotNull() {
            addCriterion("index_pe is not null");
            return (Criteria) this;
        }

        public Criteria andIndexPeEqualTo(Double value) {
            addCriterion("index_pe =", value, "indexPe");
            return (Criteria) this;
        }

        public Criteria andIndexPeNotEqualTo(Double value) {
            addCriterion("index_pe <>", value, "indexPe");
            return (Criteria) this;
        }

        public Criteria andIndexPeGreaterThan(Double value) {
            addCriterion("index_pe >", value, "indexPe");
            return (Criteria) this;
        }

        public Criteria andIndexPeGreaterThanOrEqualTo(Double value) {
            addCriterion("index_pe >=", value, "indexPe");
            return (Criteria) this;
        }

        public Criteria andIndexPeLessThan(Double value) {
            addCriterion("index_pe <", value, "indexPe");
            return (Criteria) this;
        }

        public Criteria andIndexPeLessThanOrEqualTo(Double value) {
            addCriterion("index_pe <=", value, "indexPe");
            return (Criteria) this;
        }

        public Criteria andIndexPeIn(List<Double> values) {
            addCriterion("index_pe in", values, "indexPe");
            return (Criteria) this;
        }

        public Criteria andIndexPeNotIn(List<Double> values) {
            addCriterion("index_pe not in", values, "indexPe");
            return (Criteria) this;
        }

        public Criteria andIndexPeBetween(Double value1, Double value2) {
            addCriterion("index_pe between", value1, value2, "indexPe");
            return (Criteria) this;
        }

        public Criteria andIndexPeNotBetween(Double value1, Double value2) {
            addCriterion("index_pe not between", value1, value2, "indexPe");
            return (Criteria) this;
        }

        public Criteria andWeekInfoIsNull() {
            addCriterion("week_info is null");
            return (Criteria) this;
        }

        public Criteria andWeekInfoIsNotNull() {
            addCriterion("week_info is not null");
            return (Criteria) this;
        }

        public Criteria andWeekInfoEqualTo(Integer value) {
            addCriterion("week_info =", value, "weekInfo");
            return (Criteria) this;
        }

        public Criteria andWeekInfoNotEqualTo(Integer value) {
            addCriterion("week_info <>", value, "weekInfo");
            return (Criteria) this;
        }

        public Criteria andWeekInfoGreaterThan(Integer value) {
            addCriterion("week_info >", value, "weekInfo");
            return (Criteria) this;
        }

        public Criteria andWeekInfoGreaterThanOrEqualTo(Integer value) {
            addCriterion("week_info >=", value, "weekInfo");
            return (Criteria) this;
        }

        public Criteria andWeekInfoLessThan(Integer value) {
            addCriterion("week_info <", value, "weekInfo");
            return (Criteria) this;
        }

        public Criteria andWeekInfoLessThanOrEqualTo(Integer value) {
            addCriterion("week_info <=", value, "weekInfo");
            return (Criteria) this;
        }

        public Criteria andWeekInfoIn(List<Integer> values) {
            addCriterion("week_info in", values, "weekInfo");
            return (Criteria) this;
        }

        public Criteria andWeekInfoNotIn(List<Integer> values) {
            addCriterion("week_info not in", values, "weekInfo");
            return (Criteria) this;
        }

        public Criteria andWeekInfoBetween(Integer value1, Integer value2) {
            addCriterion("week_info between", value1, value2, "weekInfo");
            return (Criteria) this;
        }

        public Criteria andWeekInfoNotBetween(Integer value1, Integer value2) {
            addCriterion("week_info not between", value1, value2, "weekInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoIsNull() {
            addCriterion("date_info is null");
            return (Criteria) this;
        }

        public Criteria andDateInfoIsNotNull() {
            addCriterion("date_info is not null");
            return (Criteria) this;
        }

        public Criteria andDateInfoEqualTo(Date value) {
            addCriterion("date_info =", value, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoNotEqualTo(Date value) {
            addCriterion("date_info <>", value, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoGreaterThan(Date value) {
            addCriterion("date_info >", value, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoGreaterThanOrEqualTo(Date value) {
            addCriterion("date_info >=", value, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoLessThan(Date value) {
            addCriterion("date_info <", value, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoLessThanOrEqualTo(Date value) {
            addCriterion("date_info <=", value, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoIn(List<Date> values) {
            addCriterion("date_info in", values, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoNotIn(List<Date> values) {
            addCriterion("date_info not in", values, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoBetween(Date value1, Date value2) {
            addCriterion("date_info between", value1, value2, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateInfoNotBetween(Date value1, Date value2) {
            addCriterion("date_info not between", value1, value2, "dateInfo");
            return (Criteria) this;
        }

        public Criteria andDateUpdateIsNull() {
            addCriterion("date_update is null");
            return (Criteria) this;
        }

        public Criteria andDateUpdateIsNotNull() {
            addCriterion("date_update is not null");
            return (Criteria) this;
        }

        public Criteria andDateUpdateEqualTo(Date value) {
            addCriterion("date_update =", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateNotEqualTo(Date value) {
            addCriterion("date_update <>", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateGreaterThan(Date value) {
            addCriterion("date_update >", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("date_update >=", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateLessThan(Date value) {
            addCriterion("date_update <", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateLessThanOrEqualTo(Date value) {
            addCriterion("date_update <=", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateIn(List<Date> values) {
            addCriterion("date_update in", values, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateNotIn(List<Date> values) {
            addCriterion("date_update not in", values, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateBetween(Date value1, Date value2) {
            addCriterion("date_update between", value1, value2, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateNotBetween(Date value1, Date value2) {
            addCriterion("date_update not between", value1, value2, "dateUpdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_net_worth_last
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 27 15:39:41 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_net_worth_last
     *
     * @mbggenerated Fri Sep 27 15:39:41 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public class BoundBuilder {
        protected Integer limit;

        protected Integer offset;

        public Integer limit() {
            return this.limit;
        }

        public BoundBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }

        public Integer offset() {
            return this.offset;
        }

        public BoundBuilder offset(Integer offset) {
            this.offset = offset;
            return this;
        }

        public TNetWorthLastCriteria build() {
            TNetWorthLastCriteria.this.limit = limit;
            TNetWorthLastCriteria.this.offset = offset;
            return TNetWorthLastCriteria.this;
        }
    }
}