package com.zsh.labouCapital.dao.dto;

import java.io.Serializable;

public class TTest implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.id
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.temp
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    private String temp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_test
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.id
     *
     * @return the value of t_test.id
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.id
     *
     * @param id the value for t_test.id
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.temp
     *
     * @return the value of t_test.temp
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    public String getTemp() {
        return temp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.temp
     *
     * @param temp the value for t_test.temp
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    public void setTemp(String temp) {
        this.temp = temp == null ? null : temp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated Wed Aug 14 19:05:35 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", temp=").append(temp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}